-- generated by axon — do not edit:
--   axon catalog manifests/ --service orders > sql-catalog/orders/R__catalog.sql
--
-- `R__`, Flyway's repeatable prefix: this file is regenerated WHOLE from the
-- manifest, so adding a value to a list changes its checksum. As a versioned
-- migration that is a mismatch and nothing gets applied; as a repeatable one it
-- is re-run, which is exactly what adding a value means.
--
-- The seed is an UPSERT and the delete is explicit: a value removed from the
-- manifest has to disappear from the table, or the list the code knows and the
-- list the database enforces stop being the same list —which is the whole
-- reason for declaring it.

CREATE TABLE IF NOT EXISTS "catalog_role" (
  name text NOT NULL PRIMARY KEY,
  description text NOT NULL
);
INSERT INTO "catalog_role" (name, description)
VALUES
  ('admin', 'Todo'),
  ('support', 'Lee y puede actuar en nombre de un cliente')
ON CONFLICT (name) DO UPDATE SET
  description = EXCLUDED.description;
DELETE FROM "catalog_role" WHERE name NOT IN ('admin', 'support');

CREATE TABLE IF NOT EXISTS "catalog_plan" (
  code text NOT NULL PRIMARY KEY,
  name text NOT NULL
);
INSERT INTO "catalog_plan" (code, name)
VALUES
  ('free', 'Gratis'),
  ('pro', 'Pro')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name;
DELETE FROM "catalog_plan" WHERE code NOT IN ('free', 'pro');

CREATE TABLE IF NOT EXISTS "catalog_currency" (
  code text NOT NULL PRIMARY KEY,
  name text NOT NULL,
  decimals bigint NOT NULL
);
INSERT INTO "catalog_currency" (code, name, decimals)
VALUES
  ('MXN', 'Peso mexicano', 2),
  ('USD', 'US Dollar', 2),
  ('CLP', 'Peso chileno', 0)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  decimals = EXCLUDED.decimals;
DELETE FROM "catalog_currency" WHERE code NOT IN ('MXN', 'USD', 'CLP');
