// generated by axon — do not edit.
//
// Wire it up from your own test file:
//
//   import { contractTests, machineTests } from "./axon.testkit.ts";
//   import { Payments } from "./index.ts";
//   contractTests((bus, inbox, outbox) => new Payments(bus, inbox, outbox));
//   machineTests();
//   errorTests();
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import {
  newEnvelope,
  type Envelope,
  type Bus,
  type Inbox,
  PaymentsService,
  type Outbox,
  Clients,
  type Transport,
  AxonProblem,
  declaredErrors,
  fail,
  problem,
  type OrderPlacedV1,
  paymentTransitions,
  paymentNext,
  paymentCan,
  type PaymentState,
  type PaymentAction,
} from "./contracts.ts";

// In-memory doubles. Deterministic and dependency-free: contract tests
// need no infrastructure, integration tests do.
export class FakeBus implements Bus {
  readonly published: Envelope<unknown>[] = [];
  async publish(e: Envelope<unknown>) {
    this.published.push(e);
  }
}

export class MemoryInbox implements Inbox {
  readonly seen = new Set<string>();
  async once(id: string, fn: () => Promise<void>) {
    if (this.seen.has(id)) return;
    this.seen.add(id);
    await fn();
  }
}

export class FakeOutbox implements Outbox<unknown> {
  readonly staged: Envelope<unknown>[] = [];
  async stage(e: Envelope<unknown>, _tx: unknown) {
    this.staged.push(e);
  }
}

/** What each declared dependency answers by default: a fixture of ITS
 *  contract, cut down to what this service declared it reads. */
export const declaredAnswers: Record<string, unknown> = {
  "orders.getOrder": { orderId: "00000000-0000-4000-8000-000000000000", status: "status", total: { amount: 100, currency: "MXN" } },
  "stripe.charges.create": { id: "id", status: "status" },
};

/** A transport that answers the contract and records what was asked of it.
 *
 *  `on` replaces one answer and `failWith` makes it fail, which is how the
 *  declared policy gets exercised without a network: a retriable failure has
 *  to arrive 1 + retries times and a final one exactly once. */
export class FakeTransport implements Transport {
  readonly calls: { target: string; method: string; body: unknown }[] = [];
  readonly #answers = new Map<string, (body: unknown) => unknown>();
  readonly #failures = new Map<string, unknown>();

  on(target: string, method: string, fn: (body: unknown) => unknown) {
    this.#answers.set(`${target}.${method}`, fn);
    return this;
  }

  failWith(target: string, method: string, err: unknown) {
    this.#failures.set(`${target}.${method}`, err);
    return this;
  }

  /** How many times one method was really called. */
  timesCalled(target: string, method: string) {
    return this.calls.filter((c) => c.target === target && c.method === method).length;
  }

  async call(target: string, method: string, body: unknown, _h: Record<string, string>) {
    this.calls.push({ target, method, body });
    const key = `${target}.${method}`;
    const failure = this.#failures.get(key);
    if (failure) throw failure;
    const custom = this.#answers.get(key);
    if (custom) return custom(body);
    const declared = declaredAnswers[key];
    if (declared === undefined) {
      throw new Error(`${key} is not a declared dependency of payments`);
    }
    return declared;
  }
}

/** The generated clients over the double: the declared timeout, retries and
 *  breaker all running, with no network. */
export const fakeClients = (t: FakeTransport = new FakeTransport()) =>
  [new Clients(t), t] as const;

// Fixtures derived from the schema declared by each event's OWNER, not
// from what the consumer believes it receives: that is where drift shows up.
export const fixtureOrderPlacedV1: OrderPlacedV1 = {
  orderId: "00000000-0000-4000-8000-000000000000",
  total: { amount: 100, currency: "MXN" },
};

/** Contract tests. `make` returns your implementation of the service. */
export function contractTests(make: (bus: FakeBus, inbox: MemoryInbox, outbox: FakeOutbox) => PaymentsService) {
  const setUp = () => {
    const bus = new FakeBus();
    const inbox = new MemoryInbox();
    const outbox = new FakeOutbox();
    const svc = make(bus, inbox, outbox);
    return { svc, bus, inbox, outbox };
  };

  describe("payments · contract", () => {
    it("accepts order.placed@v1 exactly as its owner emits it", async () => {
      const { svc } = setUp();
      await svc.dispatch(newEnvelope("order.placed@v1", "test", fixtureOrderPlacedV1));
    });

    it("a second delivery of order.placed@v1 does not repeat the effect", async () => {
      const { svc, outbox } = setUp();
      const e = newEnvelope("order.placed@v1", "test", fixtureOrderPlacedV1);
      await svc.dispatch(e);
      const after = outbox.staged.length;
      await svc.dispatch(e);
      assert.equal(outbox.staged.length, after, "the same envelope took effect twice");
    });
    it("propagates the causal chain when reacting to order.placed@v1", async () => {
      const { svc, outbox } = setUp();
      const cause = newEnvelope("order.placed@v1", "test", fixtureOrderPlacedV1);
      await svc.dispatch(cause);
      const out = outbox.staged;
      assert.ok(out.length > 0, "it emitted nothing");
      for (const e of out) {
        assert.equal(e.causationId, cause.id, "causationId does not point at the cause");
        assert.equal(e.correlationId, cause.correlationId, "the flow was lost");
        assert.equal(e.traceparent.split("-")[1], cause.traceparent.split("-")[1], "the trace was lost");
      }
    });
    it("nothing gets published outside the outbox", async () => {
      const { bus } = setUp();
      assert.equal(bus.published.length, 0, "dual-write: the handler touched the bus");
    });
  });
}

/** State machine tests. They need none of your code. */
export function machineTests() {
  describe("payments · machine payment", () => {
    it("every declared transition is legal from its source states", () => {
      for (const [action, t] of Object.entries(paymentTransitions)) {
        for (const from of t.from) {
          assert.equal(paymentNext(from, action as PaymentAction), t.to);
          assert.ok(paymentCan(from, action as PaymentAction));
        }
      }
    });

    it("an undeclared transition blows up", () => {
      const states: PaymentState[] = ["pending", "captured", "failed", "refunded"];
      for (const [action, t] of Object.entries(paymentTransitions)) {
        for (const e of states.filter((s) => !t.from.includes(s))) {
          assert.throws(() => paymentNext(e, action as PaymentAction));
          assert.equal(paymentCan(e, action as PaymentAction), false);
        }
      }
    });
  });
}

/** Tests for the declared failures. They need none of your code. */
export function errorTests() {
  describe("payments · declared failures", () => {
    it("`fail` throws the status and the code the manifest declares", () => {
      for (const [method, failures] of Object.entries(declaredErrors)) {
        for (const f of failures) {
          assert.throws(
            () => fail(method as keyof typeof declaredErrors, f.code as never),
            (err: unknown) => {
              assert.ok(err instanceof AxonProblem, `${method}.${f.code} is not an AxonProblem`);
              assert.equal(err.code, f.code);
              assert.equal(err.status, f.status);
              return true;
            },
          );
        }
      }
    });

    it("the body on the wire carries that same code and status", () => {
      for (const [method, failures] of Object.entries(declaredErrors)) {
        for (const f of failures) {
          try {
            fail(method as keyof typeof declaredErrors, f.code as never);
          } catch (err) {
            const body = problem(err, newEnvelope("test", "test", {}));
            assert.equal(body.status, f.status, `${f.code} goes out with another status`);
            assert.equal(body.title, f.code, "the code does not travel in the body");
            assert.match(body.type, /payments/, "the type does not name the service that failed");
            assert.ok(body.traceId, "the failure goes out with no trace");
          }
        }
      }
    });

    it("an undeclared failure does not come out looking declared", () => {
      const body = problem(new Error("the disk filled up"));
      assert.equal(body.status, 500, "a failure nobody declared came out as something else");
      assert.equal(body.title, "internal");
      assert.ok(!("code" in body), "it invented a code for a failure nobody declared");
    });

    it("nothing final is offered as retriable", () => {
      // A 4xx says the request is what is wrong: sending it again ends the
      // same way, and the caller's client would spend its budget for nothing.
      const notYet = [408, 425, 429];
      for (const failures of Object.values(declaredErrors)) {
        for (const f of failures) {
          assert.ok(f.status >= 400 && f.status < 600, `${f.code} is not a failure`);
          if (f.retriable && f.status < 500) {
            assert.ok(notYet.includes(f.status), `${f.code} is retriable on ${f.status}`);
          }
        }
      }
    });
  });
}

