// generated by axon from orders.toml — do not edit


/** CloudEvents envelope + causal chain. Traceability is not optional: no
 *  message leaves the process without traceparent, correlationId and causationId. */
export interface Envelope<T> {
  id: string;
  type: string;
  source: string;
  time: string;
  traceparent: string;        // W3C: 00-<trace>-<span>-<flags>
  correlationId: string;      // stable across the whole business flow
  causationId: string | null; // id of the message that caused this one
  data: T;
}

const hex = (n: number) =>
  Array.from(crypto.getRandomValues(new Uint8Array(n)), b => b.toString(16).padStart(2, "0")).join("");

export function newEnvelope<T>(type: string, source: string, data: T, cause?: Envelope<unknown>): Envelope<T> {
  const parts = cause?.traceparent.split("-");
  const trace = parts?.[1] ?? hex(16);
  // The flags are inherited, not invented: declaring "sampled" over a trace
  // that is not leaves fragments hanging off a parent that was never exported.
  const flags = parts?.[3] ?? "01";
  return {
    id: crypto.randomUUID(),
    type, source, data,
    time: new Date().toISOString(),
    traceparent: `00-${trace}-${hex(8)}-${flags}`,
    correlationId: cause ? cause.correlationId : crypto.randomUUID(),
    causationId: cause ? cause.id : null,
  };
}

export interface Bus { publish(e: Envelope<unknown>): Promise<void>; }

/** Transactional outbox: the event is saved in the same transaction as the
 *  state change, and a relay publishes it afterwards.
 *
 *  `tx` is the CALLER's transaction, and it is mandatory. On a connection of
 *  its own, a `stage` commits by itself: if the caller's transaction rolls
 *  back, the state change does not happen and the event DOES, and the relay
 *  publishes something that never occurred. That is exactly the dual-write the
 *  outbox exists to avoid, and it shows up nowhere until somebody asks about
 *  an event with no row.
 *
 *  The type stays open because the framework does not pick a database client. */
export interface Outbox<Tx = unknown> { stage(e: Envelope<unknown>, tx: Tx): Promise<void>; }

/** Idempotent inbox / consumer: the broker delivers at least once, the effect
 *  happens exactly once. `once` does not re-run an id it has already seen. */
export interface Inbox { once(id: string, fn: () => Promise<void>): Promise<void>; }

/** A failure the other side DECLARED, carried as RFC 7807.
 *
 *  It is the difference between "it failed" and "it failed for this reason":
 *  the `code` is part of the callee's contract, like a field name, so a caller
 *  can match on it instead of parsing prose out of a 500. Whoever implements
 *  `Transport` throws this when the response is a `problem+json`; three lines,
 *  and the framework still does not pick a transport. */
export class AxonProblem extends Error {
  readonly status: number;
  readonly code: string;
  readonly detail?: string;
  constructor(status: number, code: string, detail?: string) {
    super(`${code} (${status})`);
    this.status = status;
    this.code = code;
    this.detail = detail;
  }
}

export interface OrderPlacedV1 {
  orderId: string;
  customerId: string;
  customerEmail: string;
  total: { amount: number; currency: string };
}

export interface PlaceOrderIn {
  tenantId: string;
  customerId: string;
  customerEmail: string;
  total: { amount: number; currency: string };
}

export interface PlaceOrderOut {
  orderId: string;
}

export interface GetOrderIn {
  tenantId: string;
  orderId: string;
}

export interface GetOrderOut {
  orderId: string;
  status: string;
  total: { amount: number; currency: string };
}

export interface GetOrderV2In {
  tenantId: string;
  orderId: string;
}

export interface GetOrderV2Out {
  orderId: string;
  status: string;
  total: { amount: number; currency: string };
  customerId: string;
}

export const manifest = {
  "service": "orders",
  "version": "2.0.0",
  "owner": "commerce-team",
  "tier": "1",
  "pii": [
    "customer_email"
  ],
  "external": false,
  "emits": {
    "order.placed@v1": {
      "orderId": "uuid",
      "customerId": "uuid",
      "customerEmail": "string",
      "total": "money"
    }
  },
  "consumes": {},
  "methods": {
    "placeOrder": {
      "in": {
        "tenantId": "uuid",
        "customerId": "uuid",
        "customerEmail": "string",
        "total": "money"
      },
      "out": {
        "orderId": "uuid"
      },
      "http": "POST /v1/tenants/{tenantId}/orders",
      "idempotent": true,
      "auth": "public",
      "rate_limit": 60,
      "timeout_ms": 5000,
      "paginated": false,
      "errors": [
        {
          "code": "order_rejected",
          "status": 422,
          "retriable": false,
          "detail": "the order does not pass the rules"
        }
      ],
      "deprecated": null,
      "sunset": null,
      "successor": null,
      "at": {}
    },
    "getOrder": {
      "in": {
        "tenantId": "uuid",
        "orderId": "uuid"
      },
      "out": {
        "orderId": "uuid",
        "status": "string",
        "total": "money"
      },
      "http": "GET /v1/tenants/{tenantId}/orders/{orderId}",
      "idempotent": false,
      "auth": "required",
      "rate_limit": null,
      "timeout_ms": 2000,
      "paginated": false,
      "errors": [],
      "deprecated": "2026-09-01",
      "sunset": "2027-12-31",
      "successor": "getOrderV2",
      "at": {}
    },
    "getOrderV2": {
      "in": {
        "tenantId": "uuid",
        "orderId": "uuid"
      },
      "out": {
        "orderId": "uuid",
        "status": "string",
        "total": "money",
        "customerId": "uuid"
      },
      "http": "GET /v2/tenants/{tenantId}/orders/{orderId}",
      "idempotent": false,
      "auth": "required",
      "rate_limit": null,
      "timeout_ms": 2000,
      "paginated": false,
      "errors": [],
      "deprecated": null,
      "sunset": null,
      "successor": null,
      "at": {}
    }
  },
  "depends": [
    {
      "service": "payments",
      "external": null,
      "method": "capturePayment",
      "via": null,
      "timeout_ms": 3000,
      "retries": 2,
      "breaker": true,
      "uses": null
    }
  ],
  "patterns": {
    "outbox": false
  },
  "cap": {
    "consistency": "eventual",
    "on_partition": "degrade",
    "max_staleness_ms": 3000
  },
  "flags": {
    "free_shipping": {
      "owner": "orders-team",
      "variants": {
        "off": 0,
        "over_500": 50000
      },
      "default_variant": "off",
      "expires": "2027-06-30",
      "default": false,
      "rollout": null,
      "sticky_by": null,
      "kill_switch": false
    }
  },
  "analytics": {
    "export": true,
    "pii": "hash",
    "warehouse": "clickhouse"
  },
  "api": {
    "versioning": null,
    "header": null,
    "default": null,
    "support_window_days": null,
    "lts_window_days": null,
    "version": []
  },
  "pooler": {
    "engine": "pgdog",
    "mode": "transaction",
    "shards": 4,
    "max_client_conn": 500,
    "pool_size": 40,
    "cross_shard_disabled": true,
    "tenant_binding": "set_local"
  },
  "machine": {},
  "saga": {},
  "aggregate": {},
  "view": {},
  "metrics": {
    "orders_placed": {
      "on": [
        "order.placed@v1"
      ],
      "kind": "count",
      "field": null,
      "by": [],
      "window": "1d"
    },
    "orders_by_currency": {
      "on": [
        "order.placed@v1"
      ],
      "kind": "count",
      "field": null,
      "by": [
        "total.currency"
      ],
      "window": "1d"
    },
    "gmv": {
      "on": [
        "order.placed@v1"
      ],
      "kind": "sum",
      "field": "total",
      "by": [
        "total.currency"
      ],
      "window": "1d"
    }
  },
  "rules": {
    "gmv_usd_cayendo": {
      "metric": "gmv",
      "where": {
        "total.currency": "USD"
      },
      "compare": "previous",
      "below": 0.85,
      "above": null,
      "value": null,
      "for": 2,
      "cooldown": 3,
      "guard": [
        {
          "metric": "orders_by_currency",
          "where": {
            "total.currency": "USD"
          },
          "compare": null,
          "below": null,
          "above": 0.9,
          "value": null
        }
      ],
      "mode": "propose",
      "then": {
        "flag": "free_shipping",
        "variant": "over_500",
        "restore": "off",
        "emits": null,
        "calls": null
      }
    }
  },
  "infra": {
    "state": "postgres",
    "runtime": "container",
    "schedule": null,
    "migrations": "sql/orders/",
    "secrets": [],
    "min_instances": null,
    "max_instances": null,
    "port": null,
    "buckets": {},
    "pool_size": 4,
    "max_connections": 100,
    "ha": null,
    "backup_retention_days": 14,
    "pitr": null,
    "read_replicas": 2,
    "shard_key": "tenant_id",
    "tenant_column": "tenant_id",
    "tenant_exempt": []
  },
  "env": {
    "staging": {
      "state": null,
      "runtime": null,
      "schedule": null,
      "migrations": null,
      "secrets": [],
      "min_instances": 0,
      "max_instances": null,
      "port": null,
      "buckets": {},
      "pool_size": null,
      "max_connections": null,
      "ha": null,
      "backup_retention_days": null,
      "pitr": null,
      "read_replicas": null,
      "shard_key": null,
      "tenant_column": null,
      "tenant_exempt": []
    },
    "prod": {
      "state": null,
      "runtime": null,
      "schedule": null,
      "migrations": null,
      "secrets": [],
      "min_instances": 2,
      "max_instances": null,
      "port": null,
      "buckets": {},
      "pool_size": null,
      "max_connections": null,
      "ha": null,
      "backup_retention_days": null,
      "pitr": null,
      "read_replicas": null,
      "shard_key": null,
      "tenant_column": null,
      "tenant_exempt": []
    }
  }
} as const;

export abstract class OrdersService {
  protected readonly bus: Bus;
  constructor(bus: Bus) {
    this.bus = bus;
  }
  static readonly wellKnown = "/.well-known/axon.json";
  protected emitOrderPlacedV1(data: OrderPlacedV1, cause?: Envelope<unknown>) {
    return this.bus.publish(newEnvelope("order.placed@v1", "orders", data, cause));
  }
  abstract placeOrder(input: PlaceOrderIn, e: Envelope<unknown>): Promise<PlaceOrderOut>;
  abstract getOrder(input: GetOrderIn, e: Envelope<unknown>): Promise<GetOrderOut>;
  abstract getOrderV2(input: GetOrderV2In, e: Envelope<unknown>): Promise<GetOrderV2Out>;
}


/** HTTP routes the manifest declares. Startup must fail if any of them
 *  has no handler: a 404 in production tells nobody. */
export const httpRoutes = ["POST /v1/tenants/{tenantId}/orders", "GET /v1/tenants/{tenantId}/orders/{orderId}", "GET /v2/tenants/{tenantId}/orders/{orderId}"] as const;


/** Headers of a retired version, by route. The router adds them to
 *  whatever it answers: `Deprecation` (RFC 9745), `Sunset` (RFC 8594) and
 *  the successor as a `Link` (RFC 8288).
 *
 *  Deprecated is not gone: the route keeps answering what it always
 *  answered, and it says so on the way out. */
export const retiredRoutes: Record<string, Record<string, string>> = {
  "GET /v1/tenants/{tenantId}/orders/{orderId}": { "deprecation": "@1788220800", "sunset": "Fri, 31 Dec 2027 00:00:00 GMT", "link": "</v2/tenants/{tenantId}/orders/{orderId}>; rel=\"successor-version\"" },
};



/** The CAP side declared in the manifest: eventual/degrade.
 *  The isolation level follows from it: paying twice costs more than
 *  retrying, and serving stale data costs less than serving nothing. */
export const isolationLevel = "READ COMMITTED" as const;
/** Staleness budget: data older than this does not get served. */
export const maxStalenessMs = 3000;


/** The failures declared in the manifest, by method. */
export const declaredErrors = {
  placeOrder: [
    { code: "order_rejected", status: 422, retriable: false, detail: "the order does not pass the rules" },
  ],
} as const;

type Declared = typeof declaredErrors;
type Code<M extends keyof Declared> = Declared[M][number]["code"];

/** Throws a DECLARED failure. The code is checked against the manifest,
 *  so a handler cannot invent one: an undeclared code does not compile, and
 *  that is what keeps the caller's `retriable` from lying. */
export function fail<M extends keyof Declared>(method: M, code: Code<M>, detail?: string): never {
  const f = (declaredErrors[method] as readonly { code: string; status: number; detail?: string }[])
    .find((f) => f.code === code)!;
  throw new AxonProblem(f.status, f.code, detail ?? f.detail);
}

/** The body that goes out on the wire: RFC 7807, with the code and the
 *  trace. An undeclared error becomes a 500 with no code, because saying
 *  `unknown` about a failure nobody declared is the honest answer. */
export function problem(err: unknown, e?: Envelope<unknown>) {
  const p = err instanceof AxonProblem ? err : null;
  return {
    type: p ? `about:axon/orders/${p.code}` : "about:blank",
    title: p ? p.code : "internal",
    status: p ? p.status : 500,
    ...(p?.detail ? { detail: p.detail } : {}),
    ...(e ? { traceId: e.traceparent.split("-")[1] } : {}),
  };
}


/** Flag provider, with OpenFeature's shape: `evaluate` takes the name,
 *  the default value and the context it is pinned by. The standard's four
 *  types, so the real SDK fits with no translation. */
export interface Flags {
  evaluate<T extends boolean | string | number | object>(
    name: string,
    fallback: T,
    context: Record<string, string>,
  ): Promise<T>;
}

/** `free_shipping`: OpenFeature number.
 *  Variantes: `off` = 0, `over_500` = 50000.
 */
export const flagFreeShipping = (flags: Flags): Promise<number> =>
  flags.evaluate("free_shipping", 0, {});

/** The flags the manifest declares. A flag that is not here does not exist. */
export const declaredFlags = ["free_shipping"] as const;


/** Everything needed to reach another service. Implemented by whoever
 *  deploys: HTTP, gRPC, an SDK. The framework does not pick a transport. */
export interface Transport {
  call(target: string, method: string, body: unknown, headers: Record<string, string>): Promise<unknown>;
}

export class TimedOut extends Error {}
export class CircuitOpen extends Error {}

/** The policy declared in the manifest. The generator emits it; nobody types it. */
export interface Policy {
  timeoutMs: number;
  retries: number;
  breaker: boolean;
}

/** One breaker per target: when the other side goes down, stop hitting it.
 *  After the cooldown it goes half-open and tries exactly once. */
class Breaker {
  #failures = 0;
  #openUntil = 0;
  // explicit fields: parameter properties are TypeScript-only and do not
  // survive Node's type stripping
  readonly threshold: number;
  readonly cooldownMs: number;
  constructor(threshold = 5, cooldownMs = 10_000) {
    this.threshold = threshold;
    this.cooldownMs = cooldownMs;
  }

  allows(now: number) {
    return this.#openUntil === 0 || now >= this.#openUntil;
  }
  succeeded() {
    this.#failures = 0;
    this.#openUntil = 0;
  }
  failed(now: number) {
    this.#failures++;
    if (this.#failures >= this.threshold) this.#openUntil = now + this.cooldownMs;
  }
}

const breakers = new Map<string, Breaker>();

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

async function withTimeout<T>(p: Promise<T>, ms: number, who: string): Promise<T> {
  let t: ReturnType<typeof setTimeout>;
  const limit = new Promise<never>((_, reject) => {
    t = setTimeout(() => reject(new TimedOut(`${who}: timed out after ${ms}ms`)), ms);
  });
  try {
    return await Promise.race([p, limit]);
  } finally {
    clearTimeout(t!);
  }
}

/** Applies the declared policy. Retries are only emitted for idempotent
 *  methods: `axon verify` blocks the rest.
 *
 *  `retriable` comes from the CALLEE's declared errors, and it is what makes
 *  `[methods.*] errors` more than documentation: a failure the other side
 *  declared as not retriable is not retried at all. Retrying a declined card
 *  ends in the same answer and spends the caller's time budget on the way, and
 *  that budget is what a saga counts on to compensate in time. An error nobody
 *  declared keeps the old behaviour —retried— because an unknown failure could
 *  be the network. */
export async function withPolicy<T>(
  who: string,
  pol: Policy,
  attempt: () => Promise<T>,
  retriable: (code: string) => boolean = () => true,
): Promise<T> {
  const breaker = pol.breaker
    ? (breakers.get(who) ?? breakers.set(who, new Breaker()).get(who)!)
    : null;
  if (breaker && !breaker.allows(Date.now())) {
    throw new CircuitOpen(`${who}: circuit open`);
  }
  let last: unknown;
  for (let n = 0; n <= pol.retries; n++) {
    try {
      const r = await withTimeout(attempt(), pol.timeoutMs, who);
      breaker?.succeeded();
      return r;
    } catch (err) {
      last = err;
      breaker?.failed(Date.now());
      // A declared failure that cannot end differently: retrying is spending
      // the budget to get the same answer.
      if (err instanceof AxonProblem && !retriable(err.code)) throw err;
      if (n === pol.retries) break;
      // exponential with full jitter: without jitter every client retries at
      // the same instant and the other side never comes back up
      const ceiling = Math.min(1000 * 2 ** n, 10_000);
      await sleep(Math.random() * ceiling);
    }
  }
  throw last;
}

/** Headers of an outgoing call: the trace stays the same one. */
export function headers(e: Envelope<unknown>, idempotent: boolean): Record<string, string> {
  const h: Record<string, string> = {
    traceparent: e.traceparent,
    "x-correlation-id": e.correlationId,
    "x-causation-id": e.id,
  };
  // retrying without a key would duplicate the effect on the other side
  if (idempotent) h["idempotency-key"] = e.id;
  return h;
}

export interface PaymentsCapturePaymentIn {
  orderId: string;
  amount: { amount: number; currency: string };
}

export interface PaymentsCapturePaymentOut {
  paymentId: string;
}


/** Clients for the dependencies declared in the manifest. */
export class Clients {
  protected readonly transport: Transport;
  constructor(transport: Transport) {
    this.transport = transport;
  }
  /** payments.capturePayment · timeout 3000ms · 2 retries · breaker true
   *  declares: card_declined (402) · issuer_unavailable (503, retriable) */
  async paymentsCapturePayment(input: PaymentsCapturePaymentIn, e: Envelope<unknown>, fallback: () => Promise<PaymentsCapturePaymentOut>): Promise<PaymentsCapturePaymentOut> {
    const attempt = () => withPolicy("payments.capturePayment", { timeoutMs: 3000, retries: 2, breaker: true }, async () =>
      (await this.transport.call("payments", "capturePayment", input, headers(e, true))) as PaymentsCapturePaymentOut,
      (code) => ["issuer_unavailable"].includes(code));
    try {
      return await attempt();
    } catch {
      // declared `degrade`: serving something stale beats serving nothing
      return fallback();
    }
  }
}


/** Fields declared as PII in the manifest. */
export const piiFields = ["customer_email"] as const;

/** Replaces every PII field with "[redacted]", at any depth.
 *  Run anything through here before it reaches a log.
 *
 *  The comparison normalizes: `customer_email` declared in the manifest
 *  covers `customerEmail` in a contract and `customer-email` in a header.
 *  The same concept gets declared once. */
const normalizePii = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, "");
const pii = new Set((piiFields as readonly string[]).map(normalizePii));

export function redact<T>(value: T): T {
  if (Array.isArray(value)) return value.map(redact) as T;
  if (value === null || typeof value !== "object") return value;
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(value)) {
    out[k] = pii.has(normalizePii(k)) ? "[redacted]" : redact(v);
  }
  return out as T;
}

