// axon-gen-go — generador de Go para axon, como plugin externo.
//
// Lee {manifest, peers} en JSON por stdin y escribe Go por stdout. No importa
// nada de axon: el contrato es el JSON. Por eso un generador se puede escribir
// en cualquier lenguaje, y este esta en el lenguaje que genera.
//
//	axon build manifests/payments.toml manifests/ --lang go > payments/axon.go
package main

import (
	"encoding/json"
	"fmt"
	"go/format"
	"io"
	"os"
	"sort"
	"strings"
)

type Method struct {
	In         map[string]string `json:"in"`
	Out        map[string]string `json:"out"`
	HTTP       *string           `json:"http"`
	Idempotent bool              `json:"idempotent"`
}

type Consume struct {
	Handler string `json:"handler"`
}

type Transition struct {
	From  []string `json:"from"`
	To    string   `json:"to"`
	On    string   `json:"on"`
	Emits *string  `json:"emits"`
}

type Machine struct {
	Initial     string                `json:"initial"`
	Final       []string              `json:"final"`
	Transitions map[string]Transition `json:"transitions"`
}

type Manifest struct {
	Service  string                       `json:"service"`
	Emits    map[string]map[string]string `json:"emits"`
	Consumes map[string]Consume           `json:"consumes"`
	Methods  map[string]Method            `json:"methods"`
	Machine  map[string]Machine           `json:"machine"`
	Patterns struct {
		Outbox bool `json:"outbox"`
	} `json:"patterns"`
}

type Input struct {
	Manifest Manifest   `json:"manifest"`
	Peers    []Manifest `json:"peers"`
}

func main() {
	raw, err := io.ReadAll(os.Stdin)
	if err != nil {
		fatal(err)
	}
	var in Input
	if err := json.Unmarshal(raw, &in); err != nil {
		fatal(fmt.Errorf("entrada invalida: %w", err))
	}
	out, err := generar(in)
	if err != nil {
		fatal(err)
	}
	// gofmt desde stdlib: la salida de un generador no deberia necesitar que
	// nadie la formatee despues, y un error aqui delata Go invalido.
	limpio, err := format.Source([]byte(out))
	if err != nil {
		fatal(fmt.Errorf("el codigo generado no es Go valido: %w", err))
	}
	os.Stdout.Write(limpio)
}

func fatal(err error) {
	fmt.Fprintf(os.Stderr, "axon-gen-go: %v\n", err)
	os.Exit(1)
}

// Los mapas de Go no tienen orden: se ordena para que la salida sea
// determinista y `git diff --exit-code` en CI signifique algo.
func claves[V any](m map[string]V) []string {
	ks := make([]string, 0, len(m))
	for k := range m {
		ks = append(ks, k)
	}
	sort.Strings(ks)
	return ks
}

func goTipo(t string) string {
	switch t {
	case "int":
		return "int64"
	case "float":
		return "float64"
	case "bool":
		return "bool"
	case "timestamp":
		return "time.Time"
	case "json":
		return "json.RawMessage"
	case "money":
		return "Money"
	default: // string, uuid
		return "string"
	}
}

var iniciales = map[string]string{"id": "ID", "url": "URL", "api": "API", "http": "HTTP"}

func exportado(s string) string {
	var b strings.Builder
	for _, w := range strings.FieldsFunc(s, func(r rune) bool {
		return r == '.' || r == '@' || r == '_' || r == '-'
	}) {
		// camelCase -> PascalCase respetando las mayusculas internas
		w = strings.ToUpper(w[:1]) + w[1:]
		if u, ok := iniciales[strings.ToLower(w)]; ok {
			w = u
		}
		b.WriteString(w)
	}
	return b.String()
}

// Convencion de Go: orderId se escribe OrderID, no OrderId.
func campo(s string) string {
	out := exportado(s)
	for _, suf := range []string{"Id"} {
		if strings.HasSuffix(out, suf) {
			out = strings.TrimSuffix(out, suf) + "ID"
		}
	}
	return out
}

func structDe(nombre string, campos map[string]string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "type %s struct {\n", nombre)
	for _, k := range claves(campos) {
		fmt.Fprintf(&b, "\t%s %s `json:%q`\n", campo(k), goTipo(campos[k]), k)
	}
	b.WriteString("}\n")
	return b.String()
}

const cabecera = `// Code generated by axon-gen-go. DO NOT EDIT.

package %s

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"strings"
	"time"
)

// Money es un tipo propio a proposito: un float para dinero es un bug
// esperando su turno.
type Money struct {
	Amount   int64  ` + "`json:\"amount\"`" + `
	Currency string ` + "`json:\"currency\"`" + `
}

// Envelope: CloudEvents mas la cadena causal. La trazabilidad no es opcional.
type Envelope struct {
	ID            string          ` + "`json:\"id\"`" + `
	Type          string          ` + "`json:\"type\"`" + `
	Source        string          ` + "`json:\"source\"`" + `
	Time          string          ` + "`json:\"time\"`" + `
	Traceparent   string          ` + "`json:\"traceparent\"`" + `
	CorrelationID string          ` + "`json:\"correlationId\"`" + `
	CausationID   *string         ` + "`json:\"causationId\"`" + `
	Data          json.RawMessage ` + "`json:\"data\"`" + `
}

type Bus interface{ Publish(ctx context.Context, e Envelope) error }

// Outbox: el evento se guarda en la misma transaccion que el cambio de estado.
type Outbox interface{ Stage(ctx context.Context, e Envelope) error }

// Inbox: el broker entrega al menos una vez, el efecto ocurre una sola.
type Inbox interface {
	Once(ctx context.Context, id string, fn func(context.Context) error) error
}

func aleatorio(n int) string {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		panic(err)
	}
	return hex.EncodeToString(b)
}

func uuid4() string {
	b := make([]byte, 16)
	if _, err := rand.Read(b); err != nil {
		panic(err)
	}
	b[6] = (b[6] & 0x0f) | 0x40
	b[8] = (b[8] & 0x3f) | 0x80
	return fmt.Sprintf("%%x-%%x-%%x-%%x-%%x", b[0:4], b[4:6], b[6:8], b[8:10], b[10:16])
}

// NewEnvelope propaga la cadena causal: el trace se hereda, el span es nuevo,
// y causationId apunta al mensaje que provoco este.
func NewEnvelope(tipo, source string, data any, cause *Envelope) (Envelope, error) {
	payload, err := json.Marshal(data)
	if err != nil {
		return Envelope{}, err
	}
	trace, correlation := aleatorio(16), uuid4()
	var causation *string
	if cause != nil {
		if partes := strings.SplitN(cause.Traceparent, "-", 4); len(partes) >= 2 {
			trace = partes[1]
		}
		correlation = cause.CorrelationID
		id := cause.ID
		causation = &id
	}
	return Envelope{
		ID: uuid4(), Type: tipo, Source: source,
		Time:          time.Now().UTC().Format(time.RFC3339Nano),
		Traceparent:   fmt.Sprintf("00-%%s-%%s-01", trace, aleatorio(8)),
		CorrelationID: correlation, CausationID: causation, Data: payload,
	}, nil
}
`

func generar(in Input) (string, error) {
	m := in.Manifest
	var b strings.Builder
	fmt.Fprintf(&b, cabecera, strings.ReplaceAll(m.Service, "-", ""))

	// eventos emitidos
	for _, ev := range claves(m.Emits) {
		b.WriteString("\n" + structDe(exportado(ev), m.Emits[ev]))
	}
	// eventos consumidos: el esquema lo declara su EMISOR
	for _, ev := range claves(m.Consumes) {
		if _, propio := m.Emits[ev]; propio {
			continue
		}
		campos, duenio := buscarEmisor(in.Peers, ev)
		if campos == nil {
			return "", fmt.Errorf("consume %q y no se encontro quien lo emite", ev)
		}
		fmt.Fprintf(&b, "\n// %s: esquema declarado por %s, su dueno\n", ev, duenio)
		b.WriteString(structDe(exportado(ev), campos))
	}
	for _, nombre := range claves(m.Methods) {
		me := m.Methods[nombre]
		b.WriteString("\n" + structDe(exportado(nombre)+"In", me.In))
		b.WriteString(structDe(exportado(nombre) + "Out", me.Out))
	}

	b.WriteString(handlers(m))
	b.WriteString(servicio(m))
	b.WriteString(maquinas(m))
	return b.String(), nil
}

func buscarEmisor(peers []Manifest, ev string) (map[string]string, string) {
	for _, p := range peers {
		if campos, ok := p.Emits[ev]; ok {
			return campos, p.Service
		}
	}
	return nil, ""
}

// En Go la logica de negocio se implementa contra una interfaz, no heredando.
func handlers(m Manifest) string {
	var b strings.Builder
	fmt.Fprintf(&b, "\n// %sHandlers es lo que escribe la persona.\ntype %sHandlers interface {\n",
		exportado(m.Service), exportado(m.Service))
	for _, ev := range claves(m.Consumes) {
		fmt.Fprintf(&b, "\t// consume %s\n\t%s(ctx context.Context, e Envelope, data %s) error\n",
			ev, exportado(m.Consumes[ev].Handler), exportado(ev))
	}
	for _, n := range claves(m.Methods) {
		fmt.Fprintf(&b, "\t%s(ctx context.Context, in %sIn, e Envelope) (%sOut, error)\n",
			exportado(n), exportado(n), exportado(n))
	}
	b.WriteString("}\n")
	return b.String()
}

func servicio(m Manifest) string {
	tipo := exportado(m.Service) + "Service"
	sink := "s.bus.Publish"
	campos := "bus Bus\n\tinbox Inbox"
	args := "bus Bus, inbox Inbox"
	asigna := "bus: bus, inbox: inbox"
	if m.Patterns.Outbox {
		sink = "s.outbox.Stage"
		campos += "\n\toutbox Outbox"
		args += ", outbox Outbox"
		asigna += ", outbox: outbox"
	}
	var b strings.Builder
	fmt.Fprintf(&b, "\ntype %s struct {\n\t%s\n\th %sHandlers\n}\n\n", tipo, campos, exportado(m.Service))
	fmt.Fprintf(&b, "func New%s(%s, h %sHandlers) *%s {\n\treturn &%s{%s, h: h}\n}\n",
		tipo, args, exportado(m.Service), tipo, tipo, asigna)

	for _, ev := range claves(m.Emits) {
		fmt.Fprintf(&b, `
func (s *%s) Emit%s(ctx context.Context, data %s, cause *Envelope) error {
	e, err := NewEnvelope(%q, %q, data, cause)
	if err != nil {
		return err
	}
	return %s(ctx, e)
}
`, tipo, exportado(ev), exportado(ev), ev, m.Service, sink)
	}

	if len(m.Consumes) > 0 {
		fmt.Fprintf(&b, `
// Dispatch es el punto de entrada unico: deduplica por id y rutea por tipo.
func (s *%s) Dispatch(ctx context.Context, e Envelope) error {
	return s.inbox.Once(ctx, e.ID, func(ctx context.Context) error {
		switch e.Type {
`, tipo)
		for _, ev := range claves(m.Consumes) {
			fmt.Fprintf(&b, `		case %q:
			var data %s
			if err := json.Unmarshal(e.Data, &data); err != nil {
				return err
			}
			return s.h.%s(ctx, e, data)
`, ev, exportado(ev), exportado(m.Consumes[ev].Handler))
		}
		fmt.Fprintf(&b, `		default:
			return fmt.Errorf(%q, e.Type)
		}
	})
}
`, m.Service+": tipo no declarado en el manifiesto: %s")
	}
	return b.String()
}

func maquinas(m Manifest) string {
	var b strings.Builder
	for _, nombre := range claves(m.Machine) {
		mac := m.Machine[nombre]
		N := exportado(nombre)
		fmt.Fprintf(&b, "\ntype %sState string\ntype %sAction string\n\n", N, N)
		fmt.Fprintf(&b, "var %sTransitions = map[%sAction]struct {\n\tFrom []%sState\n\tTo   %sState\n\tOn   string\n}{\n",
			N, N, N, N)
		for _, act := range claves(mac.Transitions) {
			t := mac.Transitions[act]
			desde := make([]string, len(t.From))
			for i, f := range t.From {
				desde[i] = fmt.Sprintf("%q", f)
			}
			fmt.Fprintf(&b, "\t%q: {From: []%sState{%s}, To: %q, On: %q},\n",
				act, N, strings.Join(desde, ", "), t.To, t.On)
		}
		b.WriteString("}\n")
		fmt.Fprintf(&b, `
// %sNext falla si la transicion no esta declarada en el manifiesto.
func %sNext(state %sState, action %sAction) (%sState, error) {
	t, ok := %sTransitions[action]
	if !ok {
		return "", fmt.Errorf("%s: accion desconocida: %%s", action)
	}
	for _, f := range t.From {
		if f == state {
			return t.To, nil
		}
	}
	return "", fmt.Errorf("%s: %%s no es legal desde %%s", action, state)
}

func %sCan(state %sState, action %sAction) bool {
	_, err := %sNext(state, action)
	return err == nil
}
`, N, N, N, N, N, N, nombre, nombre, N, N, N, N)
	}
	return b.String()
}
