-- generated by axon — do not edit:
--   axon rls manifests/ > sql-policies/<service>/R__rls.sql
--
-- `R__`, Flyway's repeatable prefix, and not a version: a policy file is
-- regenerated WHOLE from the manifest, so its checksum changes whenever a
-- `pii` field or a `tenant_column` does. As a versioned migration that is a
-- checksum mismatch and nothing gets applied; as a repeatable one Flyway
-- re-runs it, which is exactly what regenerating means. Every statement
-- here tolerates being applied twice.
--
-- This goes in `sql-policies/`, NOT in `sql/`, and is applied after the
-- migrations. Two reasons: a policy is not a schema change, and `axon
-- verify` reads `sql/` with a SQL parser that does not understand `DO $$`.
-- The local target already ships the job that applies it to every node.
--
-- HOW THE TENANT IS PINNED, and why it matters as much as the policy:
--
--   BEGIN;
--   SET LOCAL axon.tenant = '<uuid>';   -- LOCAL, not a bare SET
--   ... the queries ...
--   COMMIT;
--
-- Measured against Postgres 16, not inferred:
--   * clean connection + only SET LOCAL -> after the COMMIT the GUC is UNSET
--   * one session `SET`, once           -> after the COMMIT, SET LOCAL reverts to THAT
--     value, not to nothing. The leak persists even if the rest of the code uses
--     SET LOCAL correctly, until somebody does RESET ALL or the connection recycles.
--
-- Hence the rule, which is stronger than "use SET LOCAL": NEVER a session `SET`
-- on `axon.tenant`, anywhere. A single one poisons the connection for everyone
-- who comes after, and if there is a pooler in transaction mode in front, the
-- next request —from ANOTHER tenant— gets that connection with the previous
-- value set. That raises no error: it returns the wrong tenant's rows.
--
-- And the role matters as much as the policy: a SUPERUSER or a role with
-- BYPASSRLS skips EVERY policy, and FORCE ROW LEVEL SECURITY does not fix it.
-- That is why this migration creates `axon_app` and grants it the permissions.
-- Measured: querying as the superuser owner, the policy filters NOTHING and
-- the result is identical to a database with no RLS. The `SET LOCAL ROLE
-- axon_app` is what switches it on, and it goes next to the tenant's in the same transaction.
--
-- What this migration CANNOT guarantee: `set_config()` with a bound parameter
-- —what several ORMs emit— may not be intercepted by a pooler; literal `SET
-- LOCAL` was preferred.

-- The role the application queries with. Without LOGIN on purpose: you
-- come in with the deploy role and adopt this one inside the
-- transaction, next to the tenant, and both die at the COMMIT:
--
--   BEGIN;
--   SET LOCAL ROLE axon_app;            -- stop being a superuser
--   SET LOCAL axon.tenant = '<uuid>';   -- and become a tenant
--   ... the queries ...
--   COMMIT;
--
-- Without this the policy exists and does not apply: the default role
-- of a freshly created Postgres is a superuser, and the application
-- "works" locally while seeing every row of every tenant.
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'axon_app') THEN
    CREATE ROLE axon_app NOLOGIN NOSUPERUSER NOBYPASSRLS;
  END IF;
END $$;

-- payments.payment: per-tenant isolation
ALTER TABLE "payment" ENABLE ROW LEVEL SECURITY;
-- FORCE: the policy applies to the table's owner too, which is
-- who usually skips it without noticing.
ALTER TABLE "payment" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "payment_tenant" ON "payment";
CREATE POLICY "payment_tenant" ON "payment"
  USING ("tenant_id" = NULLIF(current_setting('axon.tenant', true), '')::uuid)
  WITH CHECK ("tenant_id" = NULLIF(current_setting('axon.tenant', true), '')::uuid);
-- The permissions go to the application's role, not the owner: the
-- owner has FORCE on top, but a superuser skips the policy and no
-- clause fixes that. With this the policy has somebody to apply to.
GRANT SELECT, INSERT, UPDATE, DELETE ON "payment" TO axon_app;

-- payments.payment_attempt: per-tenant isolation
ALTER TABLE "payment_attempt" ENABLE ROW LEVEL SECURITY;
-- FORCE: the policy applies to the table's owner too, which is
-- who usually skips it without noticing.
ALTER TABLE "payment_attempt" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "payment_attempt_tenant" ON "payment_attempt";
CREATE POLICY "payment_attempt_tenant" ON "payment_attempt"
  USING ("tenant_id" = NULLIF(current_setting('axon.tenant', true), '')::uuid)
  WITH CHECK ("tenant_id" = NULLIF(current_setting('axon.tenant', true), '')::uuid);
-- The permissions go to the application's role, not the owner: the
-- owner has FORCE on top, but a superuser skips the policy and no
-- clause fixes that. With this the policy has somebody to apply to.
GRANT SELECT, INSERT, UPDATE, DELETE ON "payment_attempt" TO axon_app;

-- payments.payout: per-tenant isolation
ALTER TABLE "payout" ENABLE ROW LEVEL SECURITY;
-- FORCE: the policy applies to the table's owner too, which is
-- who usually skips it without noticing.
ALTER TABLE "payout" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "payout_tenant" ON "payout";
CREATE POLICY "payout_tenant" ON "payout"
  USING ("tenant_id" = NULLIF(current_setting('axon.tenant', true), '')::uuid)
  WITH CHECK ("tenant_id" = NULLIF(current_setting('axon.tenant', true), '')::uuid);
-- The permissions go to the application's role, not the owner: the
-- owner has FORCE on top, but a superuser skips the policy and no
-- clause fixes that. With this the policy has somebody to apply to.
GRANT SELECT, INSERT, UPDATE, DELETE ON "payout" TO axon_app;
