#!/bin/sh
# The integration guide, for the page. It is the real output of `axon docs`
# over `examples/`, not a copy of it: a sample pasted by hand is a sample that
# goes stale the first time the generator changes a word, and nothing fails.
#
# Run before `mdbook build`. The result is committed too, so a local build
# works without running this first; CI overwrites it, so what gets published
# is always what the compiler in that commit really prints.
set -eu

cd "$(dirname "$0")/.."
out="docs/src/integration.md"
axon="${AXON:-cargo run --quiet --release --}"

{
  printf '<!-- Generated by docs/integration.sh from examples/. Do not edit. -->\n'
  $axon docs examples/ --service orders
  printf '\n---\n\n'
  printf 'This page is the output of a command, run on every deploy:\n\n'
  printf '```sh\naxon docs examples/ --service orders\n```\n\n'
  printf 'The manifest behind it is [`examples/orders.toml`]'
  printf '(https://github.com/Andrew-Tellez/axon/blob/main/examples/orders.toml).\n'
  printf 'Nothing here was written for the page —that is the point. A guide '
  printf 'somebody maintains by hand is a guide that disagrees with the\n'
  printf 'service the first time either one moves.\n'
} > "$out"

echo "wrote $out"
