//! The warnings a repo has already decided to live with, for now.
//!
//! `verify` is all-or-nothing, and that is what keeps it out of an existing
//! codebase: the first run on a repo with twenty services prints two hundred
//! warnings, nobody reads them, and the tool gets turned off in a week. The
//! same thing happens to a linter without a suppressions file.
//!
//! What this adds is a line: today's warnings are accepted, and the next one is
//! not. Two things keep it from becoming a place where warnings go to be
//! forgotten:
//!
//! - Its presence IS the opt-in. With the file there, a warning that is not in
//!   it fails the build. Nobody has to remember a flag.
//! - An accepted warning that no longer happens gets reported. The list can
//!   only shrink without somebody noticing, never grow.
use crate::manifest::Manifest;
use serde::{Deserialize, Serialize};
use std::path::Path;

pub const ARCHIVO: &str = "axon.accepted.json";

#[derive(Debug, Default, Serialize, Deserialize)]
pub struct Accepted {
    /// A note for whoever opens the file with no context.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub note: String,
    /// The exact messages. Not a rule id, because there are none: the message
    /// IS the rule here, and an axon that changes its wording makes this file
    /// stale on purpose — running `axon accept` again is a diff somebody reads
    /// in the PR, which is the same deal as the baseline of contracts.
    #[serde(default)]
    pub warnings: Vec<String>,
}

pub fn tomar(ms: &[Manifest], warnings: &[String]) -> Accepted {
    Accepted {
        note: format!(
            "Warnings accepted for now, over {} services. Generated by `axon accept`. \
             With this file present, a warning that is not here fails the build: the \
             list is the line, and it is meant to shrink.",
            ms.len()
        ),
        warnings: warnings.to_vec(),
    }
}

pub fn cargar(dir: &Path) -> Option<Accepted> {
    let text = std::fs::read_to_string(dir.join(ARCHIVO)).ok()?;
    serde_json::from_str(&text).ok()
}

/// Splits what came out of `verify` against what was accepted.
///
/// Returns (new, accepted, stale): the ones nobody has seen, the ones already
/// on the list, and the entries on the list that no longer happen.
pub fn partir<'a>(
    warnings: &'a [String],
    accepted: &'a Accepted,
) -> (Vec<&'a String>, usize, Vec<&'a String>) {
    let nuevas: Vec<&String> = warnings
        .iter()
        .filter(|w| !accepted.warnings.contains(w))
        .collect();
    let vigentes = warnings.len() - nuevas.len();
    let stale: Vec<&String> = accepted
        .warnings
        .iter()
        .filter(|a| !warnings.contains(a))
        .collect();
    (nuevas, vigentes, stale)
}
