//! Baseline: the contracts already published.
//!
//! Without this, `verify` only detects TWO services declaring the same event
//! differently. It does not detect the most common and most expensive thing:
//! changing a field on a version that is already in production, with deployed
//! consumers expecting it as it was. A published version is immutable, and that
//! can only be checked against a record of what was published.
use crate::manifest::*;
use indexmap::IndexMap;
use serde::{Deserialize, Serialize};
use std::path::Path;

pub const ARCHIVO: &str = "axon.baseline.json";

#[derive(Debug, Serialize, Deserialize)]
pub struct Evento {
    pub owner: String,
    pub fields: Fields,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Firma {
    #[serde(rename = "in")]
    pub input: Fields,
    #[serde(rename = "out")]
    pub output: Fields,
    pub http: Option<String>,
}

#[derive(Debug, Default, Serialize, Deserialize)]
pub struct Baseline {
    /// A note for whoever opens the file with no context.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub note: String,
    #[serde(default)]
    pub events: IndexMap<String, Evento>,
    /// Keyed by `service.method`.
    #[serde(default)]
    pub methods: IndexMap<String, Firma>,
}

pub fn tomar(ms: &[Manifest]) -> Baseline {
    let mut b = Baseline {
        note: "Published contracts. Generated by `axon baseline`. A change here is \
               a breaking change: it gets reviewed in the PR like any other."
            .into(),
        ..Default::default()
    };
    for m in ms.iter().filter(|m| !m.external) {
        for (ev, fields) in &m.emits {
            b.events.insert(
                ev.clone(),
                Evento {
                    owner: m.service.clone(),
                    fields: fields.clone(),
                },
            );
        }
        for (name, me) in &m.methods {
            b.methods.insert(
                format!("{}.{name}", m.service),
                Firma {
                    input: me.input.clone(),
                    output: me.output.clone(),
                    http: me.http.clone(),
                },
            );
        }
    }
    b.events.sort_keys();
    b.methods.sort_keys();
    b
}

pub fn cargar(dir: &Path) -> Option<Baseline> {
    let f = dir.join(ARCHIVO);
    let text = std::fs::read_to_string(&f).ok()?;
    match serde_json::from_str(&text) {
        Ok(b) => Some(b),
        Err(e) => {
            eprintln!("axon: {}: baseline invalido: {e}", f.display());
            std::process::exit(1);
        }
    }
}

/// Compares the declared against the published. It only looks backwards: a new
/// event or method is not a problem, changing an old one is.
pub fn comparar(ms: &[Manifest], b: &Baseline) -> (Vec<String>, Vec<String>) {
    let mut errors = Vec::new();
    let mut warnings = Vec::new();
    let ahora = tomar(ms);

    // A contract that is not registered is not protected: tomorrow a field can
    // change on it and nobody will notice.
    let nuevos: Vec<&String> = ahora
        .events
        .keys()
        .filter(|k| !b.events.contains_key(*k))
        .chain(ahora.methods.keys().filter(|k| !b.methods.contains_key(*k)))
        .collect();
    if !nuevos.is_empty() {
        warnings.push(format!(
            "{} contracts not recorded in {ARCHIVO} ({}); run `axon baseline` when you publish them",
            nuevos.len(),
            nuevos
                .iter()
                .take(3)
                .map(|s| s.as_str())
                .collect::<Vec<_>>()
                .join(", ")
        ));
    }

    for (ev, before) in &b.events {
        match ahora.events.get(ev) {
            None => errors.push(format!(
                "{ev}: it was published by {} and nobody emits it any more; its consumers are \
                 still deployed. If it really is being retired, remove it from {ARCHIVO} in the \
                 same PR",
                before.owner
            )),
            Some(now_) if now_.owner != before.owner => errors.push(format!(
                "{ev}: changed owner, from {} to {}; an event has exactly one owner",
                before.owner, now_.owner
            )),
            Some(now_) if now_.fields != before.fields => {
                for (field, kind) in &before.fields {
                    match now_.fields.get(field) {
                        None => errors.push(format!(
                            "{ev}: field `{field}` disappeared from a published version; \
                             publish {} instead",
                            next_version(ev)
                        )),
                        Some(t) if t != kind => errors.push(format!(
                            "{ev}.{field}: changed from `{kind}` to `{t}` in a published version; \
                             publish {} instead",
                            next_version(ev)
                        )),
                        _ => {}
                    }
                }
                for field in now_.fields.keys() {
                    if !before.fields.contains_key(field) {
                        // Every axon field is required: adding one breaks the old
                        // producers just as removing one breaks the consumers.
                        errors.push(format!(
                            "{ev}: new field `{field}` in a published version; \
                             publish {} instead",
                            next_version(ev)
                        ));
                    }
                }
            }
            _ => {}
        }
    }

    for (key, before) in &b.methods {
        match ahora.methods.get(key) {
            None => errors.push(format!(
                "{key}: it was published and no longer exists; its callers are still deployed"
            )),
            Some(now_) => {
                if now_.http != before.http {
                    let r = |o: &Option<String>| o.clone().unwrap_or_else(|| "(no route)".into());
                    errors.push(format!(
                        "{key}: the route changed from `{}` to `{}`; the clients point at the old one",
                        r(&before.http),
                        r(&now_.http)
                    ));
                }
                for (field, kind) in &before.output {
                    match now_.output.get(field) {
                        None => errors.push(format!(
                            "{key}: stopped returning `{field}`; the callers read it"
                        )),
                        Some(t) if t != kind => errors.push(format!(
                            "{key}: output `{field}` changed from `{kind}` to `{t}`"
                        )),
                        _ => {}
                    }
                }
                for (field, kind) in &now_.input {
                    match before.input.get(field) {
                        None => errors.push(format!(
                            "{key}: new input `{field}`, required; the old callers do not send it"
                        )),
                        Some(before_kind) if before_kind != kind => errors.push(format!(
                            "{key}: input `{field}` changed from `{before_kind}` to `{kind}`"
                        )),
                        _ => {}
                    }
                }
            }
        }
    }
    (errors, warnings)
}

/// `order.placed@v1` -> `order.placed@v2`
fn next_version(ev: &str) -> String {
    match ev.rsplit_once("@v") {
        Some((base, n)) => match n.parse::<u32>() {
            Ok(v) => format!("`{base}@v{}`", v + 1),
            Err(_) => format!("`{ev}` with a new version"),
        },
        None => format!("`{ev}` with a new version"),
    }
}
