//! Baseline: los contratos ya publicados.
//!
//! Sin esto, `verify` solo detecta que DOS servicios declaren el mismo evento
//! distinto. No detecta lo mas comun y lo mas caro: cambiarle un campo a una
//! version que ya esta en produccion, con consumidores desplegados que la
//! esperan como estaba. Una version publicada es inmutable, y eso solo se
//! puede comprobar contra un registro de lo que se publico.
use crate::manifest::*;
use indexmap::IndexMap;
use serde::{Deserialize, Serialize};
use std::path::Path;

pub const ARCHIVO: &str = "axon.baseline.json";

#[derive(Debug, Serialize, Deserialize)]
pub struct Evento {
    pub owner: String,
    pub fields: Fields,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Firma {
    #[serde(rename = "in")]
    pub input: Fields,
    #[serde(rename = "out")]
    pub output: Fields,
    pub http: Option<String>,
}

#[derive(Debug, Default, Serialize, Deserialize)]
pub struct Baseline {
    /// A note for whoever opens the file with no context.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub nota: String,
    #[serde(default)]
    pub events: IndexMap<String, Evento>,
    /// Keyed by `service.method`.
    #[serde(default)]
    pub methods: IndexMap<String, Firma>,
}

pub fn tomar(ms: &[Manifest]) -> Baseline {
    let mut b = Baseline {
        nota: "Published contracts. Generated by `axon baseline`. A change here is \
               a breaking change: it gets reviewed in the PR like any other."
            .into(),
        ..Default::default()
    };
    for m in ms.iter().filter(|m| !m.external) {
        for (ev, fields) in &m.emits {
            b.events.insert(
                ev.clone(),
                Evento {
                    owner: m.service.clone(),
                    fields: fields.clone(),
                },
            );
        }
        for (name, me) in &m.methods {
            b.methods.insert(
                format!("{}.{name}", m.service),
                Firma {
                    input: me.input.clone(),
                    output: me.output.clone(),
                    http: me.http.clone(),
                },
            );
        }
    }
    b.events.sort_keys();
    b.methods.sort_keys();
    b
}

pub fn cargar(dir: &Path) -> Option<Baseline> {
    let f = dir.join(ARCHIVO);
    let text = std::fs::read_to_string(&f).ok()?;
    match serde_json::from_str(&text) {
        Ok(b) => Some(b),
        Err(e) => {
            eprintln!("axon: {}: baseline invalido: {e}", f.display());
            std::process::exit(1);
        }
    }
}

/// Compara lo declarado contra lo publicado. Solo mira hacia atras: un evento
/// o metodo nuevo no es un problema, cambiar uno viejo si.
pub fn comparar(ms: &[Manifest], b: &Baseline) -> (Vec<String>, Vec<String>) {
    let mut errores = Vec::new();
    let mut avisos = Vec::new();
    let ahora = tomar(ms);

    // Un contrato que no esta registrado no esta protegido: manana se le puede
    // cambiar un campo y nadie lo va a notar.
    let nuevos: Vec<&String> = ahora
        .events
        .keys()
        .filter(|k| !b.events.contains_key(*k))
        .chain(ahora.methods.keys().filter(|k| !b.methods.contains_key(*k)))
        .collect();
    if !nuevos.is_empty() {
        avisos.push(format!(
            "{} contracts not recorded in {ARCHIVO} ({}); run `axon baseline` when you publish them",
            nuevos.len(),
            nuevos
                .iter()
                .take(3)
                .map(|s| s.as_str())
                .collect::<Vec<_>>()
                .join(", ")
        ));
    }

    for (ev, antes) in &b.events {
        match ahora.events.get(ev) {
            None => errores.push(format!(
                "{ev}: it was published by {} and nobody emits it any more; its consumers are \
                 still deployed. If it really is being retired, remove it from {ARCHIVO} in the \
                 same PR",
                antes.owner
            )),
            Some(hoy) if hoy.owner != antes.owner => errores.push(format!(
                "{ev}: changed owner, from {} to {}; an event has exactly one owner",
                antes.owner, hoy.owner
            )),
            Some(hoy) if hoy.fields != antes.fields => {
                for (campo, tipo) in &antes.fields {
                    match hoy.fields.get(campo) {
                        None => errores.push(format!(
                            "{ev}: field `{campo}` disappeared from a published version; \
                             publish {} instead",
                            siguiente(ev)
                        )),
                        Some(t) if t != tipo => errores.push(format!(
                            "{ev}.{campo}: changed from `{tipo}` to `{t}` in a published version; \
                             publish {} instead",
                            siguiente(ev)
                        )),
                        _ => {}
                    }
                }
                for campo in hoy.fields.keys() {
                    if !antes.fields.contains_key(campo) {
                        // Every axon field is required: adding one breaks the old
                        // producers just as removing one breaks the consumers.
                        errores.push(format!(
                            "{ev}: new field `{campo}` in a published version; \
                             publish {} instead",
                            siguiente(ev)
                        ));
                    }
                }
            }
            _ => {}
        }
    }

    for (clave, antes) in &b.methods {
        match ahora.methods.get(clave) {
            None => errores.push(format!(
                "{clave}: estaba publicado y ya no existe; sus llamadores siguen desplegados"
            )),
            Some(hoy) => {
                if hoy.http != antes.http {
                    let r = |o: &Option<String>| o.clone().unwrap_or_else(|| "(no route)".into());
                    errores.push(format!(
                        "{clave}: the route changed from `{}` to `{}`; the clients point at the old one",
                        r(&antes.http),
                        r(&hoy.http)
                    ));
                }
                for (campo, tipo) in &antes.output {
                    match hoy.output.get(campo) {
                        None => errores.push(format!(
                            "{clave}: stopped returning `{campo}`; the callers read it"
                        )),
                        Some(t) if t != tipo => errores.push(format!(
                            "{clave}: output `{campo}` changed from `{tipo}` to `{t}`"
                        )),
                        _ => {}
                    }
                }
                for (campo, tipo) in &hoy.input {
                    match antes.input.get(campo) {
                        None => errores.push(format!(
                            "{clave}: new input `{campo}`, required; the old callers do not send it"
                        )),
                        Some(antes_tipo) if antes_tipo != tipo => errores.push(format!(
                            "{clave}: input `{campo}` changed from `{antes_tipo}` to `{tipo}`"
                        )),
                        _ => {}
                    }
                }
            }
        }
    }
    (errores, avisos)
}

/// `order.placed@v1` -> `order.placed@v2`
fn siguiente(ev: &str) -> String {
    match ev.rsplit_once("@v") {
        Some((base, n)) => match n.parse::<u32>() {
            Ok(v) => format!("`{base}@v{}`", v + 1),
            Err(_) => format!("`{ev}` with a new version"),
        },
        None => format!("`{ev}` with a new version"),
    }
}
