//! Baseline: the contracts already published.
//!
//! Without this, `verify` only detects TWO services declaring the same event
//! differently. It does not detect the most common and most expensive thing:
//! changing a field on a version that is already in production, with deployed
//! consumers expecting it as it was. A published version is immutable, and that
//! can only be checked against a record of what was published.
use crate::manifest::*;
use indexmap::IndexMap;
use serde::{Deserialize, Serialize};
use std::path::Path;

pub const ARCHIVO: &str = "axon.baseline.json";

#[derive(Debug, Serialize, Deserialize)]
pub struct Evento {
    pub owner: String,
    pub fields: Fields,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Firma {
    #[serde(rename = "in")]
    pub input: Fields,
    #[serde(rename = "out")]
    pub output: Fields,
    pub http: Option<String>,
}

/// A workflow as published: its number and its shape.
///
/// The shape is what a worker replays. Nothing else of the flow is here on
/// purpose —a raised timeout changes no history— because a rule that demands a
/// version bump for something no instance in flight would notice gets silenced
/// wholesale.
#[derive(Debug, Serialize, Deserialize)]
pub struct Flujo {
    pub owner: String,
    #[serde(default)]
    pub version: u32,
    pub shape: Vec<String>,
}

#[derive(Debug, Default, Serialize, Deserialize)]
pub struct Baseline {
    /// A note for whoever opens the file with no context.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub note: String,
    #[serde(default)]
    pub events: IndexMap<String, Evento>,
    /// Keyed by `service.method`.
    #[serde(default)]
    pub methods: IndexMap<String, Firma>,
    /// Keyed by `service.workflow`. Only the ones with a history to break.
    #[serde(default, skip_serializing_if = "IndexMap::is_empty")]
    pub workflows: IndexMap<String, Flujo>,
    /// How many shard nodes each sharded service was published with.
    ///
    /// It is not a contract with a caller, which is what the rest of this file
    /// is, and it is recorded anyway: it is a contract with the DATA. The
    /// sharder places a row by hashing its `shard_key` modulo this number, so
    /// changing it moves every row that already exists to a different node —
    /// and the symptom is not an error, it is an empty result.
    #[serde(default, skip_serializing_if = "IndexMap::is_empty")]
    pub shards: IndexMap<String, u32>,
}

pub fn tomar(ms: &[Manifest]) -> Baseline {
    let mut b = Baseline {
        note: "Published contracts. Generated by `axon baseline`. A change here is \
               a breaking change: it gets reviewed in the PR like any other."
            .into(),
        ..Default::default()
    };
    for m in ms.iter().filter(|m| !m.external) {
        for (ev, fields) in &m.emits {
            b.events.insert(
                ev.clone(),
                Evento {
                    owner: m.service.clone(),
                    fields: fields.clone(),
                },
            );
        }
        for (name, wf) in m.workflow.iter().filter(|(_, w)| w.engine.temporal()) {
            b.workflows.insert(
                format!("{}.{name}", m.service),
                Flujo {
                    owner: m.service.clone(),
                    version: wf.version.unwrap_or(1),
                    shape: wf.shape(),
                },
            );
        }
        for (name, me) in &m.methods {
            b.methods.insert(
                format!("{}.{name}", m.service),
                Firma {
                    input: me.input.clone(),
                    output: me.output.clone(),
                    http: me.http.clone(),
                },
            );
        }
    }
    for m in ms.iter().filter(|m| !m.external) {
        if m.pooler.shards > 1 {
            b.shards.insert(m.service.clone(), m.pooler.shards);
        }
    }
    b.events.sort_keys();
    b.methods.sort_keys();
    b.shards.sort_keys();
    b
}

pub fn cargar(dir: &Path) -> Option<Baseline> {
    let f = dir.join(ARCHIVO);
    let text = std::fs::read_to_string(&f).ok()?;
    match serde_json::from_str(&text) {
        Ok(b) => Some(b),
        Err(e) => {
            eprintln!("axon: {}: baseline invalido: {e}", f.display());
            std::process::exit(1);
        }
    }
}

/// Compares the declared against the published. It only looks backwards: a new
/// event or method is not a problem, changing an old one is.
/// Who declared they read a field of an event, and who of a method's answer.
///
/// It is what turns "the consumers read it" —which the baseline used to assert
/// without being able to back it up— into a name. And when EVERY consumer
/// declared what it uses and none names the field, removing it is not a
/// breaking change: that is the difference between a contract that can evolve
/// and one that is frozen by "somebody might be using it".
fn readers<'a>(ms: &'a [Manifest], ev: &str, field: &str) -> Option<Vec<&'a str>> {
    let consumers: Vec<&Manifest> = ms
        .iter()
        .filter(|m| !m.external && m.consumes.contains_key(ev))
        .collect();
    if consumers.is_empty() || consumers.iter().any(|c| c.consumes[ev].uses.is_none()) {
        return None;
    }
    Some(
        consumers
            .iter()
            .filter(|c| c.consumes[ev].uses.iter().flatten().any(|u| u == field))
            .map(|c| c.service.as_str())
            .collect(),
    )
}

fn callers<'a>(ms: &'a [Manifest], key: &str, field: &str) -> Option<Vec<&'a str>> {
    let (svc, met) = key.split_once('.')?;
    let deps: Vec<(&Manifest, &Depend)> = ms
        .iter()
        .filter(|m| !m.external)
        .flat_map(|m| m.depends.iter().map(move |d| (m, d)))
        .filter(|(_, d)| d.target() == svc && d.method == met)
        .collect();
    if deps.is_empty() || deps.iter().any(|(_, d)| d.uses.is_none()) {
        return None;
    }
    Some(
        deps.iter()
            .filter(|(_, d)| d.uses.iter().flatten().any(|u| u == field))
            .map(|(m, _)| m.service.as_str())
            .collect(),
    )
}

pub fn comparar(ms: &[Manifest], b: &Baseline) -> (Vec<String>, Vec<String>) {
    let mut errors = Vec::new();
    let mut warnings = Vec::new();
    let ahora = tomar(ms);

    // The shard topology. Up and down are both disasters and they are not the
    // same disaster, so they do not get the same sentence.
    for (svc, ahora_n) in &ahora.shards {
        let Some(antes) = b.shards.get(svc) else {
            warnings.push(format!(
                "{svc}: `shards = {ahora_n}` is not recorded in {ARCHIVO}. Until it is, a change \
                 to the shard count is a change nothing compares against; run `axon baseline`"
            ));
            continue;
        };
        match ahora_n.cmp(antes) {
            std::cmp::Ordering::Equal => {}
            std::cmp::Ordering::Greater => errors.push(format!(
                "{svc}: published with {antes} shard nodes and now declares {ahora_n}. The \
                 sharder places a row by hashing its `shard_key` modulo that number, so every \
                 row already written now hashes to a different node: the query goes to the new \
                 one, finds nothing, and returns an empty result instead of an error. Move the \
                 data first and record the new topology with `axon baseline`, or keep {antes}"
            )),
            std::cmp::Ordering::Less => errors.push(format!(
                "{svc}: published with {antes} shard nodes and now declares {ahora_n}. The nodes \
                 that disappear are not empty: what lives on them stops being reachable, and \
                 nothing in the answer says so. Drain them first and record the new topology \
                 with `axon baseline`, or keep {antes}"
            )),
        }
    }

    // A contract that is not registered is not protected: tomorrow a field can
    // change on it and nobody will notice.
    let nuevos: Vec<&String> = ahora
        .events
        .keys()
        .filter(|k| !b.events.contains_key(*k))
        .chain(ahora.methods.keys().filter(|k| !b.methods.contains_key(*k)))
        .chain(
            ahora
                .workflows
                .keys()
                .filter(|k| !b.workflows.contains_key(*k)),
        )
        .collect();
    if !nuevos.is_empty() {
        warnings.push(format!(
            "{} contracts not recorded in {ARCHIVO} ({}); run `axon baseline` when you publish them",
            nuevos.len(),
            nuevos
                .iter()
                .take(3)
                .map(|s| s.as_str())
                .collect::<Vec<_>>()
                .join(", ")
        ));
    }

    for (ev, before) in &b.events {
        match ahora.events.get(ev) {
            None => errors.push(format!(
                "{ev}: it was published by {} and nobody emits it any more; its consumers are \
                 still deployed. If it really is being retired, remove it from {ARCHIVO} in the \
                 same PR",
                before.owner
            )),
            Some(now_) if now_.owner != before.owner => errors.push(format!(
                "{ev}: changed owner, from {} to {}; an event has exactly one owner",
                before.owner, now_.owner
            )),
            Some(now_) if now_.fields != before.fields => {
                for (field, kind) in &before.fields {
                    match now_.fields.get(field) {
                        // Removing a field is breaking BECAUSE somebody reads
                        // it. With every consumer having declared what it uses,
                        // that stops being an assumption: either it names who,
                        // or it says nobody does and lets the field go.
                        None => match readers(ms, ev, field) {
                            Some(who) if who.is_empty() => warnings.push(format!(
                                "{ev}: field `{field}` was removed and no consumer declared \
                                 reading it. Every one of them declared what it uses, so this \
                                 is not a breaking change"
                            )),
                            Some(who) => errors.push(format!(
                                "{ev}: field `{field}` disappeared from a published version and \
                                 {} reads it; publish {} instead",
                                who.join(", "),
                                next_version(ev)
                            )),
                            None => errors.push(format!(
                                "{ev}: field `{field}` disappeared from a published version; \
                                 publish {} instead",
                                next_version(ev)
                            )),
                        },
                        Some(t) if t != kind => errors.push(format!(
                            "{ev}.{field}: changed from `{kind}` to `{t}` in a published version; \
                             publish {} instead",
                            next_version(ev)
                        )),
                        _ => {}
                    }
                }
                for field in now_.fields.keys() {
                    if !before.fields.contains_key(field) {
                        // Every axon field is required: adding one breaks the old
                        // producers just as removing one breaks the consumers.
                        errors.push(format!(
                            "{ev}: new field `{field}` in a published version; \
                             publish {} instead",
                            next_version(ev)
                        ));
                    }
                }
            }
            _ => {}
        }
    }

    // The determinism rule. A worker replaying an old history against new code
    // does not fail where the change is: it fails wherever the replay stops
    // matching, and the instances already started stay stuck with nothing in
    // the logs that names the change. This is that failure, moved to before the
    // deploy.
    for (key, before) in &b.workflows {
        let Some(now_) = ahora.workflows.get(key) else {
            errors.push(format!(
                "{key}: it was published by {} and no longer exists. The instances started \
                 under it are still in flight, and a worker that does not know the flow fails \
                 them for good. If it really is being retired, drain it first and remove it \
                 from {ARCHIVO} in the same PR",
                before.owner
            ));
            continue;
        };
        if now_.shape == before.shape {
            if now_.version < before.version {
                errors.push(format!(
                    "{key}: `version` went down, from {} to {}. The number only goes \
                     forward: two shapes sharing one number is a replay that cannot tell \
                     which of them it is looking at",
                    before.version, now_.version
                ));
            }
            continue;
        }
        if now_.version > before.version {
            continue;
        }
        let (was, is) = (before.shape.len(), now_.shape.len());
        let first = before
            .shape
            .iter()
            .zip(&now_.shape)
            .position(|(a, b)| a != b)
            .map(|i| {
                format!(
                    "step {} was `{}` and is `{}`",
                    i + 1,
                    before.shape[i],
                    now_.shape[i]
                )
            })
            .unwrap_or_else(|| format!("it had {was} steps and has {is}"));
        errors.push(format!(
            "{key}: the shape changed —{first}— and it is still `version = {}`. A flow in \
             flight replays the history it started with: from the step that no longer \
             matches, it neither goes on nor compensates. Bump `version` and leave the old \
             one running until it drains",
            before.version
        ));
    }

    for (key, before) in &b.methods {
        match ahora.methods.get(key) {
            None => errors.push(format!(
                "{key}: it was published and no longer exists; its callers are still deployed"
            )),
            Some(now_) => {
                if now_.http != before.http {
                    let r = |o: &Option<String>| o.clone().unwrap_or_else(|| "(no route)".into());
                    errors.push(format!(
                        "{key}: the route changed from `{}` to `{}`; the clients point at the old one",
                        r(&before.http),
                        r(&now_.http)
                    ));
                }
                for (field, kind) in &before.output {
                    match now_.output.get(field) {
                        None => match callers(ms, key, field) {
                            Some(who) if who.is_empty() => warnings.push(format!(
                                "{key}: stopped returning `{field}` and no caller declared \
                                 reading it. Every one of them declared what it uses, so this \
                                 is not a breaking change"
                            )),
                            Some(who) => errors.push(format!(
                                "{key}: stopped returning `{field}`, which {} reads",
                                who.join(", ")
                            )),
                            None => errors.push(format!(
                                "{key}: stopped returning `{field}`; nobody declared what they \
                                 read of it, so it has to be assumed somebody does"
                            )),
                        },
                        Some(t) if t != kind => errors.push(format!(
                            "{key}: output `{field}` changed from `{kind}` to `{t}`"
                        )),
                        _ => {}
                    }
                }
                for (field, kind) in &now_.input {
                    match before.input.get(field) {
                        None => errors.push(format!(
                            "{key}: new input `{field}`, required; the old callers do not send it"
                        )),
                        Some(before_kind) if before_kind != kind => errors.push(format!(
                            "{key}: input `{field}` changed from `{before_kind}` to `{kind}`"
                        )),
                        _ => {}
                    }
                }
            }
        }
    }
    (errors, warnings)
}

/// `order.placed@v1` -> `order.placed@v2`
fn next_version(ev: &str) -> String {
    match ev.rsplit_once("@v") {
        Some((base, n)) => match n.parse::<u32>() {
            Ok(v) => format!("`{base}@v{}`", v + 1),
            Err(_) => format!("`{ev}` with a new version"),
        },
        None => format!("`{ev}` with a new version"),
    }
}
