//! Catalogs: the table, its seed and the type, from one declaration.
use crate::bi::snake;
use crate::manifest::*;

fn pg_type(kind: &str) -> &str {
    match kind {
        "int" => "bigint",
        "float" => "double precision",
        "bool" => "boolean",
        "timestamp" => "timestamptz",
        "uuid" => "uuid",
        _ => "text",
    }
}

/// A TOML value as a SQL literal. Quoting by hand and not by concatenation:
/// a catalog entry is written by a person, and a person writes `O'Brien`.
fn literal(v: &toml::Value) -> String {
    match v {
        toml::Value::String(s) => format!("'{}'", s.replace('\'', "''")),
        toml::Value::Integer(n) => n.to_string(),
        toml::Value::Float(f) => f.to_string(),
        toml::Value::Boolean(b) => b.to_string(),
        other => format!("'{}'", other.to_string().replace('\'', "''")),
    }
}

/// The catalogs of every service, as one repeatable migration per service.
///
/// `R__`, Flyway's repeatable prefix, for the same reason the policies use it:
/// the file is regenerated WHOLE from the manifest, so its checksum changes
/// whenever somebody adds a value. As a versioned migration that is a checksum
/// mismatch and nothing gets applied; as a repeatable one it is re-run, which
/// is exactly what adding a value to the list means.
pub fn build(ms: &[Manifest], only: Option<&str>) -> Result<String, String> {
    let with: Vec<&Manifest> = ms
        .iter()
        .filter(|m| !m.external && !m.catalog.is_empty())
        .filter(|m| only.is_none_or(|s| m.service == s))
        .collect();
    if with.is_empty() {
        return Err(match only {
            Some(s) => format!("`{s}` declares no `[catalog.*]`"),
            None => "no service declares a `[catalog.*]`".into(),
        });
    }
    if with.len() > 1 && only.is_none() {
        return Err(format!(
            "{} services declare catalogs ({}), and each one's goes in its own migration \
             directory. Pick one with `--service`",
            with.len(),
            with.iter()
                .map(|m| m.service.as_str())
                .collect::<Vec<_>>()
                .join(", ")
        ));
    }
    let m = with[0];
    let mut o = vec![
        "-- generated by axon — do not edit:".to_string(),
        format!(
            "--   axon catalog manifests/ --service {} > sql-catalog/{}/R__catalog.sql",
            m.service, m.service
        ),
        "--".to_string(),
        "-- `R__`, Flyway's repeatable prefix: this file is regenerated WHOLE from the".to_string(),
        "-- manifest, so adding a value to a list changes its checksum. As a versioned".to_string(),
        "-- migration that is a mismatch and nothing gets applied; as a repeatable one it"
            .to_string(),
        "-- is re-run, which is exactly what adding a value means.".to_string(),
        "--".to_string(),
        "-- The seed is an UPSERT and the delete is explicit: a value removed from the".to_string(),
        "-- manifest has to disappear from the table, or the list the code knows and the"
            .to_string(),
        "-- list the database enforces stop being the same list —which is the whole".to_string(),
        "-- reason for declaring it.".to_string(),
        String::new(),
    ];
    for (name, cat) in &m.catalog {
        let table = cat.table(name);
        let cols: Vec<String> = cat
            .fields
            .iter()
            .map(|(f, k)| {
                format!(
                    "  {} {} NOT NULL{}",
                    snake(f),
                    pg_type(k),
                    if f == &cat.key { " PRIMARY KEY" } else { "" }
                )
            })
            .collect();
        o.push(format!(
            "CREATE TABLE IF NOT EXISTS \"{table}\" (\n{}\n);",
            cols.join(",\n")
        ));
        if cat.entries.is_empty() {
            o.push(String::new());
            continue;
        }
        let names: Vec<String> = cat.fields.keys().map(|f| snake(f)).collect();
        let updates: Vec<String> = cat
            .fields
            .keys()
            .filter(|f| *f != &cat.key)
            .map(|f| format!("{c} = EXCLUDED.{c}", c = snake(f)))
            .collect();
        let rows: Vec<String> = cat
            .entries
            .iter()
            .map(|e| {
                let vals: Vec<String> = cat
                    .fields
                    .keys()
                    .map(|f| e.get(f).map(literal).unwrap_or_else(|| "NULL".into()))
                    .collect();
                format!("  ({})", vals.join(", "))
            })
            .collect();
        o.push(format!(
            "INSERT INTO \"{table}\" ({})\nVALUES\n{}\nON CONFLICT ({}) DO {};",
            names.join(", "),
            rows.join(",\n"),
            snake(&cat.key),
            match updates.is_empty() {
                true => "NOTHING".to_string(),
                false => format!("UPDATE SET\n  {}", updates.join(",\n  ")),
            }
        ));
        // What was removed from the manifest leaves the table. Without this the
        // two lists drift and the drift is invisible: the code stops offering a
        // value the database still accepts.
        let keys: Vec<String> = cat
            .entries
            .iter()
            .filter_map(|e| e.get(&cat.key).map(literal))
            .collect();
        o.push(format!(
            "DELETE FROM \"{table}\" WHERE {} NOT IN ({});",
            snake(&cat.key),
            keys.join(", ")
        ));
        o.push(String::new());
    }
    Ok(o.join("\n"))
}

/// The catalog in TypeScript: a union type and the frozen table.
///
/// The union is the half that pays for the declaration. A value that is not on
/// the list does not compile, so the code cannot offer a currency the database
/// will reject — which is the bug this exists to make impossible, not to
/// report.
pub fn build_ts(m: &Manifest) -> String {
    let mut o = Vec::new();
    for (name, cat) in &m.catalog {
        let t = pascal(name);
        let keys: Vec<String> = cat
            .entries
            .iter()
            .filter_map(|e| e.get(&cat.key))
            .map(|v| match v.as_str() {
                Some(s) => format!("\"{s}\""),
                None => v.to_string(),
            })
            .collect();
        o.push(format!(
            "/** `{name}`: the declared list. A value that is not on it does not\n \
             *  compile, so the code cannot offer what the database will reject. */\n\
             export type {t} = {};",
            match keys.is_empty() {
                true => "never".to_string(),
                false => keys.join(" | "),
            }
        ));
        let rows: Vec<String> = cat
            .entries
            .iter()
            .map(|e| {
                let fields: Vec<String> = cat
                    .fields
                    .keys()
                    .map(|f| {
                        let v = e
                            .get(f)
                            .map(|v| match v.as_str() {
                                Some(s) => format!("\"{s}\""),
                                None => v.to_string(),
                            })
                            .unwrap_or_else(|| "null".into());
                        format!("{}: {v}", camel(f))
                    })
                    .collect();
                format!("  {{ {} }},", fields.join(", "))
            })
            .collect();
        // The key column is typed as the union and not as `string`: the
        // lookup and the table then agree, and a value off the list cannot be
        // written into either.
        let shape: Vec<String> = cat
            .fields
            .iter()
            .map(|(f, k)| {
                let ty = match f == &cat.key {
                    true => t.clone(),
                    false => ts_type(k).to_string(),
                };
                format!("{}: {ty}", camel(f))
            })
            .collect();
        o.push(format!(
            "export const {} : ReadonlyArray<{{ {} }}> = Object.freeze([\n{}\n]);",
            camel(&format!("{name}_catalog")),
            shape.join("; "),
            rows.join("\n")
        ));
        o.push(format!(
            "/** Lookup by `{}`. Frozen: a catalog somebody can mutate at runtime is a\n \
             *  catalog that stops matching the table. */\n\
             export const {} = (k: {t}) => {}.find((e) => e.{} === k)!;",
            cat.key,
            camel(&format!("find_{name}")),
            camel(&format!("{name}_catalog")),
            camel(&cat.key)
        ));
    }
    o.join("\n\n")
}
