//! Data access policies: per-row RLS and per-column masked views.
//!
//! It comes from crossing two things axon already knows: the real schema (read
//! from the migrations with a SQL parser) and the fields declared PII. The
//! output is one more migration, because the schema is governed by the
//! migrations and not by a command someone runs by hand and forgets.
use crate::manifest::*;

/// The framework's own tables: they carry no tenant and no personal data.
const OWN_TABLES: [&str; 2] = ["outbox", "inbox_seen"];

/// `order` is a reserved word, and not the only one. Every identifier is quoted.
fn q(n: &str) -> String {
    format!("\"{}\"", n.replace('"', ""))
}

/// The masking rule for pg_anon, chosen by the column's TYPE.
///
/// By type and not by name, on purpose. Guessing the rule because a column is
/// called `email` is the same heuristic that makes pg_anon's `create-dict`
/// fallible, and it fails in both directions: it does not recognise `correo`
/// and it gets `email_template` wrong. The type is declared; the name is not
/// significa nada.
///
/// What axon guarantees is COVERAGE: no field declared `pii` is left without a
/// rule. The rule itself is editable —to preserve the format of an email
/// address or a phone number— and the dictionary is versioned like any other
/// archivo.
///
/// Only `md5`, `date_trunc` and the literals are used, which are Postgres's,
/// plus `anon_funcs.digest`, which pg_anon documents and installs at the
/// destination. Nothing invented: a function that does not exist makes the dump
/// fail halfway through.
fn regla_pg_anon(c: &Column) -> String {
    let n = &c.name;
    let t = c.ty.as_str();
    if t.starts_with("uuid") {
        // md5 gives 32 hex chars, which cast to uuid, and the format is
        // preserved. The inner ::text is mandatory: md5(uuid) does not exist.
        format!("md5(\\\"{n}\\\"::text)::uuid")
    } else if t.starts_with("timestamp") || t.starts_with("date") {
        // the year is kept and the rest is lost: useful for aggregates
        format!("date_trunc('year', \\\"{n}\\\")")
    } else if t.starts_with("json") {
        "'{}'::jsonb".to_string()
    } else if t.starts_with("bool") {
        "false".to_string()
    } else if t.starts_with("int")
        || t.starts_with("bigint")
        || t.starts_with("smallint")
        || t.starts_with("numeric")
        || t.starts_with("decimal")
        || t.starts_with("real")
        || t.starts_with("double")
    {
        "0".to_string()
    } else {
        format!("anon_funcs.digest(\\\"{n}\\\", 'CAMBIA_ESTE_SALT', 'sha256')")
    }
}

/// pg_anon's sensitive dictionary, derived from the same things as the views:
/// the real schema and the `pii` fields.
///
/// It solves a different problem from the views. The views protect the live
/// query: an analytics role never sees the raw data. pg_anon makes a masked
/// COPY, to populate staging or give realistic data to somebody who must not
/// see the real thing. They complement each other.
///
/// What axon adds is that the dictionary is neither written nor scanned for:
/// it comes out declared. pg_anon's `create-dict` detects sensitive data by
/// heuristic, and a heuristic gets it wrong in both directions.
pub fn build_pg_anon(ms: &[Manifest]) -> String {
    let schemas = schemas(ms);
    let mut entries = Vec::new();
    let mut excluded = Vec::new();
    for m in ms.iter().filter(|m| !m.external) {
        let Some(tables) = schemas.get(&m.service) else {
            continue;
        };
        let pii = &m.pii;
        for (t, cols) in tables {
            if OWN_TABLES.contains(&t.as_str()) {
                // The outbox carries every event's payload in a jsonb: the last
                // place anyone would look for a leak. And a copy for development
                // needs neither the pending queue nor the ids already seen.
                excluded.push(format!(
                    "        {{\"schema\": \"public\", \"table\": \"{t}\"}},  # axon's own infrastructure"
                ));
                continue;
            }
            let sensitive: Vec<&Column> =
                cols.cols.iter().filter(|c| is_pii(pii, &c.name)).collect();
            if sensitive.is_empty() {
                continue;
            }
            let fields: Vec<String> = sensitive
                .iter()
                .map(|c| format!("                \"{}\": \"{}\",", c.name, regla_pg_anon(c)))
                .collect();
            entries.push(format!(
                "        {{  # {}\n            \"schema\": \"public\",\n            \"table\": \"{t}\",\n            \"fields\": {{\n{}\n            }},\n        }},",
                m.service,
                fields.join("\n")
            ));
        }
    }
    let mut o = vec![
        "# generated by axon — do not edit. pg_anon's sensitive dictionary:".to_string(),
        "#   axon rls manifests/ --target pg_anon > sens_dict.py".to_string(),
        "#   pg_anon --mode=dump --prepared-sens-dict-file=sens_dict.py ...".to_string(),
        "#".to_string(),
        "# It comes from the manifest's `pii` fields crossed with the real schema, so".to_string(),
        "# `create-dict`'s heuristic scan is not needed: what is sensitive is".to_string(),
        "# declared, not guessed.".to_string(),
        "#".to_string(),
        "# pg_anon does pseudonymisation, not irreversible anonymisation: the copy is".to_string(),
        "# still personal data. Its own documentation says so, and it is worth".to_string(),
        "# remembering before sending it to a third party.".to_string(),
        "{".to_string(),
        "    \"dictionary\": [".to_string(),
    ];
    if entries.is_empty() {
        o.push("        # no service declares `pii` fields".to_string());
    }
    o.extend(entries);
    o.push("    ],".to_string());
    if !excluded.is_empty() {
        o.push("    \"dictionary_exclude\": [".to_string());
        o.extend(excluded);
        o.push("    ],".to_string());
    }
    o.push("}".to_string());
    o.push(String::new());
    o.join("\n")
}

pub fn build(ms: &[Manifest]) -> String {
    let schemas = schemas(ms);
    let mut o = vec![
        "-- generated by axon — do not edit:".to_string(),
        "--   axon rls manifests/ > sql-policies/<service>/R__rls.sql".to_string(),
        "--".to_string(),
        "-- `R__`, Flyway's repeatable prefix, and not a version: a policy file is".to_string(),
        "-- regenerated WHOLE from the manifest, so its checksum changes whenever a".to_string(),
        "-- `pii` field or a `tenant_column` does. As a versioned migration that is a".to_string(),
        "-- checksum mismatch and nothing gets applied; as a repeatable one Flyway".to_string(),
        "-- re-runs it, which is exactly what regenerating means. Every statement".to_string(),
        "-- here tolerates being applied twice.".to_string(),
        "--".to_string(),
        "-- This goes in `sql-policies/`, NOT in `sql/`, and is applied after the".to_string(),
        "-- migrations. Two reasons: a policy is not a schema change, and `axon".to_string(),
        "-- verify` reads `sql/` with a SQL parser that does not understand `DO $$`.".to_string(),
        "-- The local target already ships the job that applies it to every node.".to_string(),
        "--".to_string(),
        "-- HOW THE TENANT IS PINNED, and why it matters as much as the policy:".to_string(),
        "--".to_string(),
        "--   BEGIN;".to_string(),
        "--   SET LOCAL axon.tenant = '<uuid>';   -- LOCAL, not a bare SET".to_string(),
        "--   ... the queries ...".to_string(),
        "--   COMMIT;".to_string(),
        "--".to_string(),
        "-- Measured against Postgres 16, not inferred:".to_string(),
        "--   * clean connection + only SET LOCAL -> after the COMMIT the GUC is UNSET"
            .to_string(),
        "--   * one session `SET`, once           -> after the COMMIT, SET LOCAL reverts to THAT"
            .to_string(),
        "--     value, not to nothing. The leak persists even if the rest of the code uses"
            .to_string(),
        "--     SET LOCAL correctly, until somebody does RESET ALL or the connection recycles."
            .to_string(),
        "--".to_string(),
        "-- Hence the rule, which is stronger than \"use SET LOCAL\": NEVER a session `SET`"
            .to_string(),
        "-- on `axon.tenant`, anywhere. A single one poisons the connection for everyone"
            .to_string(),
        "-- who comes after, and if there is a pooler in transaction mode in front, the"
            .to_string(),
        "-- next request —from ANOTHER tenant— gets that connection with the previous".to_string(),
        "-- value set. That raises no error: it returns the wrong tenant's rows."
            .to_string(),
        "--".to_string(),
        "-- And the role matters as much as the policy: a SUPERUSER or a role with".to_string(),
        "-- BYPASSRLS skips EVERY policy, and FORCE ROW LEVEL SECURITY does not fix it."
            .to_string(),
        "-- That is why this migration creates `axon_app` and grants it the permissions."
            .to_string(),
        "-- Measured: querying as the superuser owner, the policy filters NOTHING and".to_string(),
        "-- the result is identical to a database with no RLS. The `SET LOCAL ROLE"
            .to_string(),
        "-- axon_app` is what switches it on, and it goes next to the tenant's in the same transaction."
            .to_string(),
        "--".to_string(),
        "-- What this migration CANNOT guarantee: `set_config()` with a bound parameter"
            .to_string(),
        "-- —what several ORMs emit— may not be intercepted by a pooler; literal `SET"
            .to_string(),
        "-- LOCAL` was preferred.".to_string(),
    ];
    let head = o.len();
    for m in ms.iter().filter(|m| !m.external) {
        let Some(tables) = schemas.get(&m.service) else {
            continue;
        };
        let pii = &m.pii;

        for (t, cols) in tables {
            if OWN_TABLES.contains(&t.as_str()) || m.infra.tenant_exempt.contains(t) {
                continue;
            }
            // ---- per-row RLS ----
            if let Some(tenant) = &m.infra.tenant_column {
                if cols.has(tenant) {
                    let (tq, cq) = (q(t), q(tenant));
                    o.push(format!(
                        "\n-- {svc}.{t}: per-tenant isolation\n\
                         ALTER TABLE {tq} ENABLE ROW LEVEL SECURITY;\n\
                         -- FORCE: the policy applies to the table's owner too, which is\n\
                         -- who usually skips it without noticing.\n\
                         ALTER TABLE {tq} FORCE ROW LEVEL SECURITY;\n\
                         DROP POLICY IF EXISTS {pol} ON {tq};\n\
                         CREATE POLICY {pol} ON {tq}\n  \
                           USING ({cq} = NULLIF(current_setting('axon.tenant', true), '')::uuid)\n  \
                           WITH CHECK ({cq} = NULLIF(current_setting('axon.tenant', true), '')::uuid);\n\
                         -- The permissions go to the application's role, not the owner: the\n\
                         -- owner has FORCE on top, but a superuser skips the policy and no\n\
                         -- clause fixes that. With this the policy has somebody to apply to.\n\
                         GRANT SELECT, INSERT, UPDATE, DELETE ON {tq} TO axon_app;",
                        svc = m.service,
                        pol = q(&format!("{t}_tenant")),
                    ));
                }
            }
            // ---- per-column masking ----
            let sensitive: Vec<&Column> =
                cols.cols.iter().filter(|c| is_pii(pii, &c.name)).collect();
            if !sensitive.is_empty() {
                let projection: Vec<String> = cols
                    .cols
                    .iter()
                    .map(|c| {
                        if sensitive.iter().any(|s| s.name == c.name) {
                            format!("  '[redacted]'::text AS {}", q(&c.name))
                        } else {
                            format!("  {}", q(&c.name))
                        }
                    })
                    .collect();
                let (tq, vq) = (q(t), q(&format!("{t}_masked")));
                o.push(format!(
                    "\n-- {svc}.{t}: masked view. The read role is given this one and\n\
                     -- never the table: that way an analytics SELECT * cannot leak PII.\n\
                     CREATE OR REPLACE VIEW {vq} AS SELECT\n{}\nFROM {tq};\n\
                     REVOKE ALL ON {tq} FROM axon_reader;\n\
                     GRANT SELECT ON {vq} TO axon_reader;",
                    projection.join(",\n"),
                    svc = m.service,
                ));
            }
        }
    }
    // the role is created once, not once per service
    if o.iter().skip(head).any(|l| l.contains("axon_app")) {
        o.insert(
            head,
            "\n-- The role the application queries with. Without LOGIN on purpose: you\n\
             -- come in with the deploy role and adopt this one inside the\n\
             -- transaction, next to the tenant, and both die at the COMMIT:\n\
             --\n\
             --   BEGIN;\n\
             --   SET LOCAL ROLE axon_app;            -- stop being a superuser\n\
             --   SET LOCAL axon.tenant = '<uuid>';   -- and become a tenant\n\
             --   ... the queries ...\n\
             --   COMMIT;\n\
             --\n\
             -- Without this the policy exists and does not apply: the default role\n\
             -- of a freshly created Postgres is a superuser, and the application\n\
             -- \"works\" locally while seeing every row of every tenant.\n\
             DO $$ BEGIN\n  \
               IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'axon_app') THEN\n    \
                 CREATE ROLE axon_app NOLOGIN NOSUPERUSER NOBYPASSRLS;\n  END IF;\nEND $$;"
                .to_string(),
        );
    }
    if o.len() > head && o.iter().any(|l| l.contains("axon_reader")) {
        o.insert(
            head,
            "\n-- The read role exists for analytics and support: it never sees the raw table.\n\
             DO $$ BEGIN\n  \
               IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'axon_reader') THEN\n    \
                 CREATE ROLE axon_reader NOLOGIN;\n  END IF;\nEND $$;"
                .to_string(),
        );
    }
    if o.len() <= head {
        o.push(
            "\n-- Nothing to generate: no service declares `tenant_column` or `pii` fields.".into(),
        );
    }
    o.push(String::new());
    o.join("\n")
}
