//! The Go generator, native.
//!
//! It was a plugin, and being a plugin was the point for a while: it proved
//! the protocol holds a real generator. What it could not prove is the claim
//! underneath the whole project —that the manifest is not TypeScript in
//! disguise— because nobody runs a generator they have to build first.
//!
//! It produces idiomatic Go and not translated TypeScript: an interface the
//! person implements instead of inheritance, `ctx` first and `error` last,
//! `OrderID` and not `OrderId`. The output is already `gofmt`-clean, checked
//! with the real `gofmt` and `go vet`: a generator should not leave code
//! somebody has to format afterwards.
use crate::manifest::*;

/// Go's own initialisms. `orderId` is written `OrderID`, and a generator that
/// gets this wrong produces code that reads as foreign in its own language.
const INITIALISMS: [&str; 8] = ["id", "url", "api", "http", "json", "sql", "uri", "uuid"];

fn exported(s: &str) -> String {
    s.split(['.', '@', '_', '-', ' '])
        .filter(|w| !w.is_empty())
        .map(|w| {
            let up = w.to_uppercase();
            if INITIALISMS.contains(&w.to_lowercase().as_str()) {
                return up;
            }
            let mut c = w.chars();
            match c.next() {
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

/// A field's name, with the trailing initialism Go expects: `orderId` is
/// `OrderID`.
fn field(s: &str) -> String {
    let out = exported(s);
    for suf in ["Id", "Url", "Api", "Uri"] {
        if out.ends_with(suf) && out.len() > suf.len() {
            return format!("{}{}", &out[..out.len() - suf.len()], suf.to_uppercase());
        }
    }
    out
}

/// gofmt lines up consecutive lines that have the same shape. Emitting it
/// already aligned is not cosmetics: the output has to be formatted, not
/// formattable, and `gofmt -l` in the suite is what says whether it is.
fn aligned(rows: &[Vec<String>]) -> String {
    let cols = rows.iter().map(|r| r.len()).max().unwrap_or(0);
    let width = |i: usize| {
        rows.iter()
            .filter_map(|r| r.get(i))
            .map(|c| c.chars().count())
            .max()
            .unwrap_or(0)
    };
    let widths: Vec<usize> = (0..cols).map(width).collect();
    rows.iter()
        .map(|r| {
            let mut line = String::from("\t");
            for (i, c) in r.iter().enumerate() {
                match i + 1 == r.len() {
                    true => line.push_str(c),
                    false => line.push_str(&format!(
                        "{c}{} ",
                        " ".repeat(widths[i].saturating_sub(c.chars().count()))
                    )),
                }
            }
            line
        })
        .collect::<Vec<_>>()
        .join("\n")
        + "\n"
}

fn go_type(t: &str) -> &str {
    match t {
        "int" => "int64",
        "float" => "float64",
        "bool" => "bool",
        "timestamp" => "time.Time",
        "json" => "json.RawMessage",
        "money" => "Money",
        _ => "string",
    }
}

/// A doc comment, wrapped. gofmt does not wrap comments, so a generator that
/// emits one long line leaves a long line in somebody's editor forever.
fn comment(text: &str) -> String {
    let (mut out, mut line) = (String::new(), String::from("//"));
    for w in text.split_whitespace() {
        if line.len() + 1 + w.len() > 78 {
            out.push_str(&format!("{line}\n"));
            line = String::from("//");
        }
        line.push(' ');
        line.push_str(w);
    }
    out + &line + "\n"
}

/// A struct, with the columns lined up the way `gofmt` would leave them: the
/// output has to be formatted already, not formattable.
fn struct_of(name: &str, fields: &[(&String, &String)], doc: &str) -> String {
    let mut o = String::new();
    if !doc.is_empty() {
        o.push_str(&comment(doc));
    }
    if fields.is_empty() {
        return o + &format!("type {name} struct{{}}\n\n");
    }
    let rows: Vec<Vec<String>> = fields
        .iter()
        .map(|(n, t)| vec![field(n), go_type(t).to_string(), format!("`json:\"{n}\"`")])
        .collect();
    o.push_str(&format!("type {name} struct {{\n{}}}\n\n", aligned(&rows)));
    o
}

/// `errors` only when something declares a failure: an unused import does not
/// compile in Go, which is the language saying the generator lied about what
/// it needs.
fn header(pkg: &str, needs_errors: bool) -> String {
    let errors = if needs_errors { "\n\t\"errors\"" } else { "" };
    format!(
        r#"// Code generated by axon. DO NOT EDIT.

package {pkg}

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"{errors}
	"fmt"
	"strings"
	"time"
)

// Money is its own type on purpose: a float for money is a bug waiting its
// turn.
type Money struct {{
	Amount   int64  `json:"amount"`
	Currency string `json:"currency"`
}}

// Envelope is CloudEvents plus the causal chain. Traceability is not optional.
type Envelope struct {{
	ID            string          `json:"id"`
	Type          string          `json:"type"`
	Source        string          `json:"source"`
	Time          string          `json:"time"`
	Traceparent   string          `json:"traceparent"`
	CorrelationID string          `json:"correlationId"`
	CausationID   *string         `json:"causationId"`
	Data          json.RawMessage `json:"data"`
}}

type Bus interface {{
	Publish(ctx context.Context, e Envelope) error
}}

// Outbox: the event is saved in the same transaction as the state change.
type Outbox interface {{
	Stage(ctx context.Context, e Envelope) error
}}

// Inbox: the broker delivers at least once, the effect happens once.
type Inbox interface {{
	Once(ctx context.Context, id string, fn func(context.Context) error) error
}}

func randomHex(n int) string {{
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {{
		panic(err)
	}}
	return hex.EncodeToString(b)
}}

func uuid4() string {{
	b := make([]byte, 16)
	if _, err := rand.Read(b); err != nil {{
		panic(err)
	}}
	b[6] = (b[6] & 0x0f) | 0x40
	b[8] = (b[8] & 0x3f) | 0x80
	return fmt.Sprintf("%x-%x-%x-%x-%x", b[0:4], b[4:6], b[6:8], b[8:10], b[10:16])
}}

// NewEnvelope carries the causal chain forward: the trace is inherited, the
// span is new, and causationId points at the message that caused this one.
func NewEnvelope(kind, source string, data any, cause *Envelope) (Envelope, error) {{
	payload, err := json.Marshal(data)
	if err != nil {{
		return Envelope{{}}, err
	}}
	trace, correlation := randomHex(16), uuid4()
	var causation *string
	if cause != nil {{
		if parts := strings.SplitN(cause.Traceparent, "-", 4); len(parts) >= 2 {{
			trace = parts[1]
		}}
		correlation = cause.CorrelationID
		id := cause.ID
		causation = &id
	}}
	return Envelope{{
		ID:            uuid4(),
		Type:          kind,
		Source:        source,
		Time:          time.Now().UTC().Format(time.RFC3339Nano),
		Traceparent:   fmt.Sprintf("00-%s-%s-01", trace, randomHex(8)),
		CorrelationID: correlation,
		CausationID:   causation,
		Data:          payload,
	}}, nil
}}

"#
    )
}

/// The `Problem` type itself. Both the declared failures and the generated
/// `RequireScopes` return one, so it is emitted when either exists: a
/// manifest with scopes and no declared errors used to generate code that
/// did not compile.
fn problem(m: &Manifest) -> String {
    let needed = m
        .methods
        .values()
        .any(|me| !me.errors.is_empty() || !me.scopes.is_empty());
    if !needed {
        return String::new();
    }
    String::from(
        "// Problem is what travels on the wire when something declared fails:\n\
         // RFC 7807, with the code the manifest declares.\n\
         type Problem struct {\n\
         \tStatus    int    `json:\"status\"`\n\
         \tCode      string `json:\"title\"`\n\
         \tDetail    string `json:\"detail\"`\n\
         \tRetriable bool   `json:\"-\"`\n\
         }\n\n\
         func (p *Problem) Error() string {\n\
         \tif p.Detail == \"\" {\n\
         \t\treturn p.Code\n\
         \t}\n\
         \treturn p.Code + \": \" + p.Detail\n\
         }\n\n\
         // Retriable answers the only question a caller has about a failure it\n\
         // did not expect: is trying again worth anything.\n\
         func Retriable(err error) bool {\n\
         \tvar p *Problem\n\
         \tif errors.As(err, &p) {\n\
         \t\treturn p.Retriable\n\
         \t}\n\
         \treturn false\n\
         }\n\n",
    )
}

/// RFC 7807 and the declared failures. In TypeScript an undeclared code does
/// not compile because the type is a union of literals; Go has no such type,
/// so the contract is a named string type with one constant per declared
/// failure. A conversion can still bypass it — what cannot drift is the
/// status and the `retriable` that come out of the manifest.
fn failures(m: &Manifest) -> String {
    let with: Vec<(&String, &Method)> = m
        .methods
        .iter()
        .filter(|(_, me)| !me.errors.is_empty())
        .collect();
    if with.is_empty() {
        return String::new();
    }
    let mut o = String::new();
    for (name, me) in with {
        let t = format!("{}Error", exported(name));
        o.push_str(&format!(
            "// The failures {} declares. A method that fails in a way nobody\n\
             // declared is a 500 with no code, which is the honest answer.\n\
             type {t} string\n\n\
             const (\n",
            camel(name)
        ));
        let consts: Vec<Vec<String>> = me
            .errors
            .iter()
            .map(|f| {
                vec![
                    format!("{}{}", exported(name), exported(&f.code)),
                    t.clone(),
                    format!("= {:?}", f.code),
                ]
            })
            .collect();
        o.push_str(&aligned(&consts));
        o.push_str(")\n\n");
        let rows: Vec<Vec<String>> = me
            .errors
            .iter()
            .map(|f| {
                vec![
                    format!("{:?}:", f.code),
                    format!(
                        "{{Status: {}, Code: {:?}, Detail: {:?}, Retriable: {}}},",
                        f.status,
                        f.code,
                        f.detail.clone().unwrap_or_default(),
                        f.retriable
                    ),
                ]
            })
            .collect();
        o.push_str(&format!(
            "var {}Failures = map[{t}]Problem{{\n{}}}\n\n",
            exported(name),
            aligned(&rows)
        ));
        o.push_str(&format!(
            "// Fail returns the declared failure, with its status and its\n\
             // retriable straight out of the manifest.\n\
             func (c {t}) Fail(detail string) error {{\n\
             \tp := {}Failures[c]\n\
             \tif detail != \"\" {{\n\
             \t\tp.Detail = detail\n\
             \t}}\n\
             \treturn &p\n\
             }}\n\n",
            exported(name)
        ));
    }
    o
}

/// The scopes a method demands. Declared in the manifest and not in an `if`
/// inside a handler, which is the version nobody can audit from outside.
fn scopes(m: &Manifest) -> String {
    let with: Vec<(&String, &Method)> = m
        .methods
        .iter()
        .filter(|(_, me)| !me.scopes.is_empty())
        .collect();
    if with.is_empty() {
        return String::new();
    }
    let mut o = String::from(
        "// RequireScopes answers with RFC 6750's `insufficient_scope`, and not\n\
         // with a bare 403: a caller has to be able to tell \"you are nobody\"\n\
         // from \"you are somebody who may not do this\".\n\
         func RequireScopes(granted []string, need ...string) error {\n\
         \tfor _, want := range need {\n\
         \t\tfound := false\n\
         \t\tfor _, g := range granted {\n\
         \t\t\tif g == want {\n\
         \t\t\t\tfound = true\n\
         \t\t\t\tbreak\n\
         \t\t\t}\n\
         \t\t}\n\
         \t\tif !found {\n\
         \t\t\treturn &Problem{Status: 403, Code: \"insufficient_scope\", Detail: \"requires \" + want}\n\
         \t\t}\n\
         \t}\n\
         \treturn nil\n\
         }\n\n",
    );
    for (name, me) in with {
        let list: Vec<String> = me.scopes.iter().map(|s| format!("{s:?}")).collect();
        o.push_str(&format!(
            "// {} requires {}.\nvar {}Scopes = []string{{{}}}\n\n",
            camel(name),
            me.scopes.join(", "),
            exported(name),
            list.join(", ")
        ));
    }
    o
}

/// The types of the events and methods, with one rule that is the whole point
/// of `uses`: a consumed event's type carries ONLY the fields this service
/// declared it reads. The others do not exist on this side, so the
/// declaration cannot drift from the code.
fn types(m: &Manifest, all: &[Manifest]) -> Result<String, String> {
    let mut o = String::new();
    for (ev, fields) in &m.emits {
        o.push_str(&struct_of(
            &exported(ev),
            &fields.iter().collect::<Vec<_>>(),
            &format!("{ev}, emitted by this service."),
        ));
    }
    for (ev, spec) in &m.consumes {
        if m.emits.contains_key(ev) {
            continue;
        }
        let owner = all
            .iter()
            .find(|p| p.emits.contains_key(ev))
            .ok_or_else(|| format!("{ev} is consumed and nobody emits it"))?;
        let fields = &owner.emits[ev];
        let (kept, doc) = match &spec.uses {
            Some(uses) => (
                fields
                    .iter()
                    .filter(|(n, _)| uses.contains(n))
                    .collect::<Vec<_>>(),
                format!(
                    "{ev}: schema declared by {}, its owner. Only the fields this \
                     service declared it reads: the rest do not exist on this side.",
                    owner.service
                ),
            ),
            None => (
                fields.iter().collect::<Vec<_>>(),
                format!("{ev}: schema declared by {}, its owner.", owner.service),
            ),
        };
        o.push_str(&struct_of(&exported(ev), &kept, &doc));
    }
    for (name, me) in &m.methods {
        o.push_str(&struct_of(
            &format!("{}In", exported(name)),
            &me.input.iter().collect::<Vec<_>>(),
            "",
        ));
        o.push_str(&struct_of(
            &format!("{}Out", exported(name)),
            &me.output.iter().collect::<Vec<_>>(),
            "",
        ));
    }
    // What this service reads of somebody else's answer. Same rule as `uses`
    // on an event: what was not declared is not in the type.
    for d in &m.depends {
        let (Some(uses), Some(target)) = (
            d.uses.as_ref(),
            all.iter().find(|p| p.service == d.target() && !p.external),
        ) else {
            continue;
        };
        let Some(me) = target.methods.get(&d.method) else {
            continue;
        };
        let kept: Vec<_> = me.output.iter().filter(|(n, _)| uses.contains(n)).collect();
        o.push_str(&struct_of(
            &format!("{}{}Result", exported(&target.service), exported(&d.method)),
            &kept,
            &format!(
                "What this service reads of {}.{}: only what it declared.",
                target.service, d.method
            ),
        ));
    }
    Ok(o)
}

/// In Go the business logic implements an interface; it does not inherit.
fn handlers(m: &Manifest) -> String {
    let s = exported(&m.service);
    let mut o =
        format!("// {s}Handlers is what the person writes.\ntype {s}Handlers interface {{\n");
    for (ev, spec) in &m.consumes {
        o.push_str(&format!(
            "\t// consume {ev}\n\t{}(ctx context.Context, e Envelope, data {}) error\n",
            exported(&spec.handler),
            exported(ev)
        ));
    }
    for name in m.methods.keys() {
        o.push_str(&format!(
            "\t{n}(ctx context.Context, in {n}In, e Envelope) ({n}Out, error)\n",
            n = exported(name)
        ));
    }
    o.push_str("}\n\n");
    o
}

fn service(m: &Manifest) -> String {
    let s = exported(&m.service);
    let t = format!("{s}Service");
    let (sink, mut fields, mut args, mut assign) = match m.patterns.outbox {
        true => (
            "s.outbox.Stage",
            vec![
                vec!["bus".into(), "Bus".into()],
                vec!["inbox".into(), "Inbox".into()],
                vec!["outbox".into(), "Outbox".into()],
            ],
            "bus Bus, inbox Inbox, outbox Outbox".to_string(),
            "bus: bus, inbox: inbox, outbox: outbox".to_string(),
        ),
        false => (
            "s.bus.Publish",
            vec![
                vec!["bus".into(), "Bus".into()],
                vec!["inbox".into(), "Inbox".into()],
            ],
            "bus Bus, inbox Inbox".to_string(),
            "bus: bus, inbox: inbox".to_string(),
        ),
    };
    fields.push(vec!["h".into(), format!("{s}Handlers")]);
    args.push_str(&format!(", h {s}Handlers"));
    assign.push_str(", h: h");
    let mut o = format!("type {t} struct {{\n{}}}\n\n", aligned(&fields));
    o.push_str(&format!(
        "func New{t}({args}) *{t} {{\n\treturn &{t}{{{assign}}}\n}}\n\n"
    ));
    for ev in m.emits.keys() {
        o.push_str(&format!(
            "func (s *{t}) Emit{e}(ctx context.Context, data {e}, cause *Envelope) error {{\n\
             \te, err := NewEnvelope({ev:?}, {svc:?}, data, cause)\n\
             \tif err != nil {{\n\t\treturn err\n\t}}\n\
             \treturn {sink}(ctx, e)\n}}\n\n",
            e = exported(ev),
            svc = m.service
        ));
    }
    if !m.consumes.is_empty() {
        o.push_str(&format!(
            "// Dispatch is the single entry point: it deduplicates by id and\n\
             // routes by type.\n\
             func (s *{t}) Dispatch(ctx context.Context, e Envelope) error {{\n\
             \treturn s.inbox.Once(ctx, e.ID, func(ctx context.Context) error {{\n\
             \t\tswitch e.Type {{\n"
        ));
        for (ev, spec) in &m.consumes {
            o.push_str(&format!(
                "\t\tcase {ev:?}:\n\
                 \t\t\tvar data {e}\n\
                 \t\t\tif err := json.Unmarshal(e.Data, &data); err != nil {{\n\
                 \t\t\t\treturn err\n\t\t\t}}\n\
                 \t\t\treturn s.h.{h}(ctx, e, data)\n",
                e = exported(ev),
                h = exported(&spec.handler)
            ));
        }
        o.push_str(&format!(
            "\t\tdefault:\n\t\t\treturn fmt.Errorf({:?}, e.Type)\n\t\t}}\n\t}})\n}}\n\n",
            format!("{}: type not declared in the manifest: %s", m.service)
        ));
    }
    o
}

fn machines(m: &Manifest) -> String {
    let mut o = String::new();
    for (name, mac) in &m.machine {
        let n = exported(name);
        o.push_str(&format!("type {n}State string\ntype {n}Action string\n\n"));
        o.push_str(&format!(
            "var {n}Transitions = map[{n}Action]struct {{\n\tFrom []{n}State\n\tTo   {n}State\n\tOn   string\n}}{{\n"
        ));
        let rows: Vec<Vec<String>> = mac
            .transitions
            .iter()
            .map(|(act, t)| {
                let from: Vec<String> = t.from.iter().map(|f| format!("{f:?}")).collect();
                vec![
                    format!("{act:?}:"),
                    format!(
                        "{{From: []{n}State{{{}}}, To: {:?}, On: {:?}}},",
                        from.join(", "),
                        t.to,
                        t.on
                    ),
                ]
            })
            .collect();
        o.push_str(&aligned(&rows));
        o.push_str("}\n\n");
        o.push_str(&format!(
            "// {n}Next fails if the transition is not declared in the manifest.\n\
             func {n}Next(state {n}State, action {n}Action) ({n}State, error) {{\n\
             \tt, ok := {n}Transitions[action]\n\
             \tif !ok {{\n\t\treturn \"\", fmt.Errorf({:?}, action)\n\t}}\n\
             \tfor _, f := range t.From {{\n\t\tif f == state {{\n\t\t\treturn t.To, nil\n\t\t}}\n\t}}\n\
             \treturn \"\", fmt.Errorf({:?}, action, state)\n}}\n\n\
             func {n}Can(state {n}State, action {n}Action) bool {{\n\
             \t_, err := {n}Next(state, action)\n\treturn err == nil\n}}\n\n",
            format!("{name}: unknown action: %s"),
            format!("{name}: %s is not legal from %s")
        ));
    }
    o
}

pub fn build(m: &Manifest, all: &[Manifest]) -> Result<String, String> {
    let pkg = m.service.replace(['-', '_'], "");
    let body = format!(
        "{}{}{}{}{}{}{}",
        types(m, all)?,
        problem(m),
        failures(m),
        scopes(m),
        handlers(m),
        service(m),
        machines(m)
    );
    // gofmt leaves exactly one newline at the end of a file
    Ok(format!(
        "{}{}\n",
        header(&pkg, body.contains("errors.As(")),
        body.trim_end()
    ))
}
