//! `pgdog.toml` derived from the manifest.
//!
//! What makes this generator verifiable is that pgdog publishes the JSON Schema
//! of its configuration, generated from its own Rust types and checked by its
//! CI. So the output is not compared against expected text: it is validated
//! against the real schema of the parser that will read it.
//!
//! One file PER SERVICE, not one for all of them. `[general]`, `[multi_tenant]`
//! and `[admin]` are singleton tables: emitting them twice is not a debatable
//! configuration, it is TOML that does not parse. And it matches
//! database-per-service: if two services share a pooler, they share its
//! connection queue.
use crate::manifest::*;

/// The database's logical name for the sharder: the same for every node,
/// because the client connects to ONE and pgdog picks the node.
fn base(svc: &str) -> String {
    svc.to_string()
}

/// The shard key's type, in pgdog's vocabulary.
///
/// Its enum accepts `bigint`, `uuid`, `vector` and `varchar`: if the column is
/// of another type, the sharder does not know how to hash it.
fn key_type(t: &Table, key: &str) -> Option<&'static str> {
    let c = t.col(key)?;
    let ty = c.ty.as_str();
    Some(if ty.starts_with("uuid") {
        "uuid"
    } else if ty.starts_with("bigint") || ty.starts_with("int") || ty.starts_with("smallint") {
        "bigint"
    } else if ty.starts_with("varchar") || ty.starts_with("text") || ty.starts_with("char") {
        "varchar"
    } else {
        return None;
    })
}

/// The service whose pooler is about to be emitted.
///
/// With only one there is nothing to choose. With several, choosing on the
/// user's behalf would be choosing wrong in silence: each one has its own file.
fn pick<'a>(ms: &'a [Manifest], only: Option<&str>) -> Result<&'a Manifest, String> {
    let active_ones: Vec<&Manifest> = ms
        .iter()
        .filter(|m| !m.external && m.pooler.active())
        .collect();
    match (active_ones.len(), only) {
        (0, _) => Err("no service declares `[pooler] engine`".into()),
        (_, Some(s)) => active_ones
            .into_iter()
            .find(|m| m.service == s)
            .ok_or_else(|| format!("`{s}` does not declare `[pooler] engine`")),
        (1, None) => Ok(active_ones[0]),
        (_, None) => Err(format!(
            "{} services declare a pooler ({}), and each one carries its own \
             pgdog.toml: `[general]` is a singleton table. Pick one with `--service`.",
            active_ones.len(),
            active_ones
                .iter()
                .map(|m| m.service.as_str())
                .collect::<Vec<_>>()
                .join(", ")
        )),
    }
}

/// A node's host: the container the compose brings up, or a variable.
fn host(m: &Manifest, target: &str, shard: u32) -> (String, String) {
    match target {
        "local" => (
            format!(
                "host = \"{}\"",
                crate::infra::node(&m.service, Some(m.pooler.shards.max(1)), shard)
            ),
            "port = 5432".into(),
        ),
        _ => (
            format!("host = \"${{AXON_DB_HOST_{shard}}}\""),
            format!("port = ${{AXON_DB_PORT_{shard}}}"),
        ),
    }
}

/// `users.toml`: pgdog lets nobody in who is not declared here.
///
/// The password comes from a variable except in local, where the engine the
/// compose brings up has a fixed, known one. A secret that protects nothing
/// gains nothing from living in a variable, and would lose the generated file's
/// ability to start on its own.
pub fn users(ms: &[Manifest], target: &str, only: Option<&str>) -> Result<String, String> {
    let m = pick(ms, only)?;
    let svc = &m.service;
    let key = match target {
        "local" => "password = \"local\"".to_string(),
        _ => format!(
            "password = \"${{AXON_DB_PASSWORD_{}}}\"",
            svc.to_uppercase().replace('-', "_")
        ),
    };
    Ok(format!(
        "# generated by axon — do not edit.\n\
         #   axon pooler manifests/ --service {svc} --users --target {target} > users.toml\n\
         \n\
         [[users]]\n\
         name = \"postgres\"\n\
         database = \"{base}\"\n\
         {key}\n\
         # La misma regla que en pgdog.toml, otra vez aca: el ajuste por usuario\n\
         # gana sobre el general, asi que declararlo de un only lado deja la\n\
         # puerta abierta por el otro.\n\
         cross_shard_disabled = {cross}\n",
        base = base(svc),
        cross = m.pooler.cross_shard_disabled
    ))
}

pub fn build(ms: &[Manifest], target: &str, only: Option<&str>) -> Result<String, String> {
    let m = pick(ms, only)?;
    let esquemas = schemas(ms);
    let pl = &m.pooler;
    let svc = &m.service;
    let mut o = vec![
        "# generated by axon — do not edit.".to_string(),
        format!("#   axon pooler manifests/ --service {svc} --target {target} > pgdog.toml"),
        "#".to_string(),
        match target {
            "local" => "# Los hosts son los contenedores que levanta `axon infra --target local`.",
            _ => "# Los nodos salen de variables: un archivo generado no es lugar\n\
                  # para una contrasena ni para la topologia de un entorno.",
        }
        .to_string(),
        String::new(),
        "[general]".into(),
        format!("pooler_mode = \"{}\"", pl.mode),
    ];
    if let Some(n) = pl.pool_size {
        o.push(format!("default_pool_size = {n}"));
    }
    // Rechazar antes que devolver un resultado incompleto: sin JOIN entre
    // nodos ni unicidad global, una consulta que cruza se responde mal.
    o.push(format!(
        "# rechaza la consulta que cruza nodos en vez de ejecutarla: sin JOIN entre\n\
         # nodos, lo que el sharder no sabe resolver devolveria un resultado parcial\ncross_shard_disabled = {}",
        pl.cross_shard_disabled
    ));
    if pl.shards > 1 {
        // El parser tiene que estar SIEMPRE encendido: en `auto` no se activa
        // con un only nodo primario, y ahi es justo donde una GUC de sesion se
        // cuela sin ser interceptada.
        o.push(
            "# `on` y no `auto`: en `auto` el parser no se activa con un only nodo\n\
             # primario, que es exactamente el caso donde una GUC de sesion se cuela\nquery_parser = \"on\""
                .into(),
        );
        o.push(format!(
            "# el reparto se declara en el manifiesto; aca only se refleja\n# shards = {}",
            pl.shards
        ));
    }
    o.push(String::new());

    // Un bloque `databases` por nodo.
    for shard in 0..pl.shards.max(1) {
        let (h, p) = host(m, target, shard);
        o.push("[[databases]]".into());
        o.push(format!("name = \"{}\"", base(svc)));
        o.push(h);
        o.push(p);
        o.push(format!("database_name = \"{svc}\""));
        o.push("role = \"primary\"".into());
        if pl.shards > 1 {
            o.push(format!("shard = {shard}"));
        }
        if let Some(n) = pl.pool_size {
            o.push(format!("pool_size = {n}"));
        }
        o.push(String::new());
    }
    // El compose local no levanta replicas: declararlas apuntando a un host
    // que no existe deja al pooler reintentando contra la nada.
    let replicas = match target {
        "local" => 0,
        _ => m.infra.read_replicas.unwrap_or(0),
    };
    for r in 0..replicas {
        o.push("[[databases]]".into());
        o.push(format!("name = \"{}\"", base(svc)));
        o.push(format!("host = \"${{AXON_DB_RO_HOST_{r}}}\""));
        o.push(format!("port = ${{AXON_DB_RO_PORT_{r}}}"));
        o.push(format!("database_name = \"{svc}\""));
        o.push("role = \"replica\"".into());
        o.push(String::new());
    }

    if pl.shards > 1 {
        let key = m
            .infra
            .shard_key
            .as_ref()
            .ok_or_else(|| format!("{svc}: `shards > 1` sin `shard_key`"))?;
        let tables = esquemas
            .get(svc)
            .ok_or_else(|| format!("{svc}: sin migraciones, no se puede declarar el reparto"))?;
        let mut declared = 0;
        for (t, tb) in tables {
            if ["outbox", "inbox_seen"].contains(&t.as_str()) || !tb.has(key) {
                continue;
            }
            let kind = key_type(tb, key).ok_or_else(|| {
                format!(
                    "{svc}.{t}.{key}: kind `{}` que el sharder no sabe hashear; admite \
                     uuid, bigint y varchar",
                    tb.col(key).map(|c| c.ty.as_str()).unwrap_or("?")
                )
            })?;
            o.push("[[sharded_tables]]".into());
            o.push(format!("database = \"{}\"", base(svc)));
            o.push(format!("name = \"{t}\""));
            o.push(format!("column = \"{key}\""));
            o.push(format!("data_type = \"{kind}\""));
            // el mismo hash que `PARTITION BY HASH` de Postgres, para que el
            // reparto coincida si algun dia se mueve dentro del motor
            o.push("hasher = \"postgres\"".into());
            o.push(String::new());
            declared += 1;
        }
        if declared == 0 {
            return Err(format!(
                "{svc}: ninguna tabla lleva `{key}`, asi que no hay nada que repartir"
            ));
        }
        // pgdog rutea por la columna de inquilino cuando la reconoce en la
        // consulta. Es la misma columna que sostiene la RLS generada, y
        // declararla aca es lo que hace que un inquilino viva en un nodo.
        if let Some(col) = &m.infra.tenant_column {
            o.push("[multi_tenant]".into());
            o.push(format!("column = \"{col}\""));
            o.push(String::new());
        }
    }
    Ok(o.join("\n"))
}
