//! `pgdog.toml` derived from the manifest.
//!
//! What makes this generator verifiable is that pgdog publishes the JSON Schema
//! of its configuration, generated from its own Rust types and checked by its
//! CI. So the output is not compared against expected text: it is validated
//! against the real schema of the parser that will read it.
//!
//! One file PER SERVICE, not one for all of them. `[general]`, `[multi_tenant]`
//! and `[admin]` are singleton tables: emitting them twice is not a debatable
//! configuration, it is TOML that does not parse. And it matches
//! database-per-service: if two services share a pooler, they share its
//! connection queue.
use crate::manifest::*;

/// The database's logical name for the sharder: the same for every node,
/// because the client connects to ONE and pgdog picks the node.
fn base(svc: &str) -> String {
    svc.to_string()
}

/// The shard key's type, in pgdog's vocabulary.
///
/// Its enum accepts `bigint`, `uuid`, `vector` and `varchar`: if the column is
/// of another type, the sharder does not know how to hash it.
fn key_type(t: &Table, key: &str) -> Option<&'static str> {
    let c = t.col(key)?;
    let ty = c.ty.as_str();
    Some(if ty.starts_with("uuid") {
        "uuid"
    } else if ty.starts_with("bigint") || ty.starts_with("int") || ty.starts_with("smallint") {
        "bigint"
    } else if ty.starts_with("varchar") || ty.starts_with("text") || ty.starts_with("char") {
        "varchar"
    } else {
        return None;
    })
}

/// The service whose pooler is about to be emitted.
///
/// With only one there is nothing to choose. With several, choosing on the
/// user's behalf would be choosing wrong in silence: each one has its own file.
fn pick<'a>(ms: &'a [Manifest], only: Option<&str>) -> Result<&'a Manifest, String> {
    let active_ones: Vec<&Manifest> = ms
        .iter()
        .filter(|m| !m.external && m.pooler.active())
        .collect();
    match (active_ones.len(), only) {
        (0, _) => Err("no service declares `[pooler] engine`".into()),
        (_, Some(s)) => active_ones
            .into_iter()
            .find(|m| m.service == s)
            .ok_or_else(|| format!("`{s}` does not declare `[pooler] engine`")),
        (1, None) => Ok(active_ones[0]),
        (_, None) => Err(format!(
            "{} services declare a pooler ({}), and each one carries its own \
             pgdog.toml: `[general]` is a singleton table. Pick one with `--service`.",
            active_ones.len(),
            active_ones
                .iter()
                .map(|m| m.service.as_str())
                .collect::<Vec<_>>()
                .join(", ")
        )),
    }
}

/// A node's host: the container the compose brings up, or a variable.
fn host(m: &Manifest, target: &str, shard: u32) -> (String, String) {
    match target {
        "local" => (
            format!(
                "host = \"{}\"",
                crate::infra::node(&m.service, Some(m.pooler.shards.max(1)), shard)
            ),
            "port = 5432".into(),
        ),
        _ => (
            format!("host = \"${{AXON_DB_HOST_{shard}}}\""),
            format!("port = ${{AXON_DB_PORT_{shard}}}"),
        ),
    }
}

/// `users.toml`: pgdog lets nobody in who is not declared here.
///
/// The password comes from a variable except in local, where the engine the
/// compose brings up has a fixed, known one. A secret that protects nothing
/// gains nothing from living in a variable, and would lose the generated file's
/// ability to start on its own.
pub fn users(ms: &[Manifest], target: &str, only: Option<&str>) -> Result<String, String> {
    let m = pick(ms, only)?;
    let svc = &m.service;
    let key = match target {
        "local" => "password = \"local\"".to_string(),
        _ => format!(
            "password = \"${{AXON_DB_PASSWORD_{}}}\"",
            svc.to_uppercase().replace('-', "_")
        ),
    };
    Ok(format!(
        "# generated by axon — do not edit.\n\
         #   axon pooler manifests/ --service {svc} --users --target {target} > users.toml\n\
         \n\
         [[users]]\n\
         name = \"postgres\"\n\
         database = \"{base}\"\n\
         {key}\n\
         # The same rule as in pgdog.toml, again here: the per-user setting wins\n\
         # over the general one, so declaring it on one side only leaves the door\n\
         # open on the other.\n\
         cross_shard_disabled = {cross}\n",
        base = base(svc),
        cross = m.pooler.cross_shard_disabled
    ))
}

pub fn build(ms: &[Manifest], target: &str, only: Option<&str>) -> Result<String, String> {
    let m = pick(ms, only)?;
    let esquemas = schemas(ms);
    let pl = &m.pooler;
    let svc = &m.service;
    let mut o = vec![
        "# generated by axon — do not edit.".to_string(),
        format!("#   axon pooler manifests/ --service {svc} --target {target} > pgdog.toml"),
        "#".to_string(),
        match target {
            "local" => "# The hosts are the containers `axon infra --target local` brings up.",
            _ => {
                "# The nodes come from variables: a generated file is no place for a\n\
                  # password or for an environment's topology."
            }
        }
        .to_string(),
        String::new(),
        "[general]".into(),
        format!("pooler_mode = \"{}\"", pl.mode),
    ];
    if let Some(n) = pl.pool_size {
        o.push(format!("default_pool_size = {n}"));
    }
    // Refuse rather than return an incomplete result: with no cross-node JOIN
    // and no global uniqueness, a crossing query is answered wrong.
    o.push(format!(
        "# rejects a query that crosses nodes instead of running it: with no cross-node\n\
         # JOIN, what the sharder cannot resolve would return a partial result\ncross_shard_disabled = {}",
        pl.cross_shard_disabled
    ));
    if pl.shards > 1 {
        // The parser has to be ALWAYS on: in `auto` it does not kick in with a
        // single primary node, and that is exactly where a session GUC slips
        // through without being intercepted.
        o.push(
            "# `on` and not `auto`: in `auto` the parser does not kick in with a single\n\
             # primary node, which is exactly the case where a session GUC slips through\nquery_parser = \"on\""
                .into(),
        );
        o.push(format!(
            "# the sharding is declared in the manifest; here it is only reflected\n# shards = {}",
            pl.shards
        ));
    }
    o.push(String::new());

    // One `databases` block per node.
    for shard in 0..pl.shards.max(1) {
        let (h, p) = host(m, target, shard);
        o.push("[[databases]]".into());
        o.push(format!("name = \"{}\"", base(svc)));
        o.push(h);
        o.push(p);
        o.push(format!("database_name = \"{svc}\""));
        o.push("role = \"primary\"".into());
        if pl.shards > 1 {
            o.push(format!("shard = {shard}"));
        }
        if let Some(n) = pl.pool_size {
            o.push(format!("pool_size = {n}"));
        }
        o.push(String::new());
    }
    // The local compose brings up no replicas: declaring them pointing at a
    // host that does not exist leaves the pooler retrying against nothing.
    let replicas = match target {
        "local" => 0,
        _ => m.infra.read_replicas.unwrap_or(0),
    };
    for r in 0..replicas {
        o.push("[[databases]]".into());
        o.push(format!("name = \"{}\"", base(svc)));
        o.push(format!("host = \"${{AXON_DB_RO_HOST_{r}}}\""));
        o.push(format!("port = ${{AXON_DB_RO_PORT_{r}}}"));
        o.push(format!("database_name = \"{svc}\""));
        o.push("role = \"replica\"".into());
        o.push(String::new());
    }

    if pl.shards > 1 {
        let key = m
            .infra
            .shard_key
            .as_ref()
            .ok_or_else(|| format!("{svc}: `shards > 1` with no `shard_key`"))?;
        let tables = esquemas
            .get(svc)
            .ok_or_else(|| format!("{svc}: with no migrations, the sharding cannot be declared"))?;
        let mut declared = 0;
        for (t, tb) in tables {
            if ["outbox", "inbox_seen"].contains(&t.as_str()) || !tb.has(key) {
                continue;
            }
            let kind = key_type(tb, key).ok_or_else(|| {
                format!(
                    "{svc}.{t}.{key}: kind `{}` the sharder cannot hash; it accepts \
                     uuid, bigint y varchar",
                    tb.col(key).map(|c| c.ty.as_str()).unwrap_or("?")
                )
            })?;
            o.push("[[sharded_tables]]".into());
            o.push(format!("database = \"{}\"", base(svc)));
            o.push(format!("name = \"{t}\""));
            o.push(format!("column = \"{key}\""));
            o.push(format!("data_type = \"{kind}\""));
            // the same hash as Postgres's `PARTITION BY HASH`, so the sharding
            // matches if it ever moves inside the engine
            o.push("hasher = \"postgres\"".into());
            o.push(String::new());
            declared += 1;
        }
        if declared == 0 {
            return Err(format!(
                "{svc}: no table carries `{key}`, so there is nothing to shard"
            ));
        }
        // pgdog routes by the tenant column when it recognises it in the query.
        // It is the same column the generated RLS rests on, and declaring it
        // here is what makes a tenant live on one node.
        if let Some(col) = &m.infra.tenant_column {
            o.push("[multi_tenant]".into());
            o.push(format!("column = \"{col}\""));
            o.push(String::new());
        }
    }
    Ok(o.join("\n"))
}
