// The saga's coordinator. The only hand-written parts are each step's INPUTS
// —business data— and the journal. The order, the compensation in reverse order
// and the sweep were generated by axon.
import { AxonProblem, CheckoutService, fail, problem, Clients, httpRoutes, manifest, sweepRouteCheckout, runCheckout,
         sweepCheckout, startSweepCheckout, checkoutLoad,
         checkoutSnapshot, conversionApply, pruneCheckout, newEnvelope,
         pruneRouteCheckout, rebuildConversion, rebuildRouteConversion,
         VersionConflict, SagaStuck,
         type CheckoutIn, type CheckoutOut, type CheckoutActions, type CheckoutOutputs,
         type CheckoutRules, type ConversionProjection, type Checkpoint,
         type Envelope, type SnapshottingStream, type Outbox, type SagaJournal, type SagaStatus,
         type Shadow,
         type Transport } from "./contracts.ts";
import { startTelemetry } from "../telemetry.ts";
import { bus, connectBroker, outbox, relay, serve, waitForDb } from "../runtime.ts";
import type pg from "pg";

/** HTTP against the declared services. The framework does not pick a transport:
 *  the generated client puts the timeout, the retries and the breaker on top. */
function transport(): Transport {
  return {
    async call(target, method, body, hdrs) {
      const routes: Record<string, string> = {
        capturePayment: "/v1/payments",
        refundPayment: `/v1/payments/${(body as any).paymentId}/refunds`,
        payoutMerchant: "/v1/payouts",
      };
      const r = await fetch(`http://${target}:8080${routes[method]}`, {
        method: "POST",
        headers: { "content-type": "application/json", ...hdrs },
        body: JSON.stringify(body),
      });
      if (!r.ok) {
        // A `problem+json` with a code is a failure the other side DECLARED:
        // it comes back as an AxonProblem so the generated client can decide
        // whether trying again could end differently. Three lines, and they are
        // what turn the manifest's `errors` into behaviour.
        const text = await r.text();
        const code = r.headers.get("content-type")?.includes("problem+json")
          ? (JSON.parse(text) as { title?: string }).title
          : undefined;
        if (code) throw new AxonProblem(r.status, code, text);
        throw new Error(`${target}.${method}: ${r.status} ${text}`);
      }
      return r.json();
    },
  };
}

/** The journal on Postgres.
 *
 *  `claim` is the piece that cannot be written naively: two instances sweep at
 *  the same time, and if this LISTED the stranded ones, both would take the same
 *  saga and compensate the same steps. The claim and the filter are one
 *  statement. */
class Journal implements SagaJournal {
  #db: pg.Pool;
  constructor(db: pg.Pool) {
    this.#db = db;
  }

  async open(id: string, _saga: string, e: Envelope<unknown>) {
    await this.#db.query(
      `INSERT INTO saga_checkout (id, step, status, data) VALUES ($1, 0, 'open', $2)
       ON CONFLICT (id) DO NOTHING`,
      [id, JSON.stringify(e)],
    );
  }

  async mark(id: string, step: number, status: string, output?: unknown) {
    // the output is saved in the SAME statement as the status: in two, a cut
    // between them leaves the step done and its result lost
    await this.#db.query(
      // The step's key goes as a parameter SEPARATE from the number: using the
      // same `$2` as an int and as text leaves the type ambiguous and Postgres
      // rejects it.
      `UPDATE saga_checkout
          SET step = $2::int, status = $3, updated = now(),
              outputs = CASE WHEN $5::jsonb IS NULL THEN outputs
                             ELSE coalesce(outputs, '{}'::jsonb) || jsonb_build_object($4::text, $5::jsonb) END
        WHERE id = $1`,
      [id, step, status, String(step), output === undefined ? null : JSON.stringify(output)],
    );
  }

  async close(id: string, status: SagaStatus) {
    await this.#db.query(
      `UPDATE saga_checkout SET status = $2, updated = now() WHERE id = $1`,
      [id, status],
    );
  }

  async read(id: string) {
    const { rows } = await this.#db.query(
      `SELECT step, status, coalesce(outputs, '{}'::jsonb) AS outputs
         FROM saga_checkout WHERE id = $1 AND status <> 'open'`,
      [id],
    );
    if (!rows[0]) return null;
    return {
      step: Number(rows[0].step),
      status: rows[0].status as string,
      outputs: rows[0].outputs as Record<number, unknown>,
    };
  }

  async claim(_saga: string, olderThan: Date, limit: number) {
    const { rows } = await this.#db.query(
      `UPDATE saga_checkout SET updated = now()
        WHERE id IN (
          SELECT id FROM saga_checkout
           WHERE status IN ('open','attempting','done') AND updated < $1
           ORDER BY updated
           LIMIT $2
           FOR UPDATE SKIP LOCKED
        )
        RETURNING id, data`,
      [olderThan, limit],
    );
    return rows.map((r: any) => ({ id: r.id as string, data: r.data as Envelope<unknown> }));
  }
}

/** The event stream on Postgres.
 *
 *  `append` takes the version the caller believed was current. The UNIQUE
 *  (stream_id, version) is what makes it count: if somebody else wrote in
 *  between, the insert fails and whoever gets that reads again. Without the
 *  UNIQUE both would get in and the rebuilt state would depend on the read
 *  order. */
class Stream implements SnapshottingStream {
  #db: pg.Pool;
  #outbox: Outbox<pg.PoolClient>;
  constructor(db: pg.Pool, o: Outbox<pg.PoolClient>) {
    this.#db = db;
    this.#outbox = o;
  }

  /** Only the snapshots of the current rules version. One from another version
   *  is ignored and the state is rebuilt in full: slow and correct, in that
   *  order. */
  async snapshot(streamId: string, rules: number) {
    const { rows } = await this.#db.query(
      `SELECT version, state FROM checkout_snapshot
        WHERE stream_id = $1 AND rules = $2 ORDER BY version DESC LIMIT 1`,
      [streamId, rules],
    );
    return rows[0] ? { version: Number(rows[0].version), state: rows[0].state } : null;
  }

  async saveSnapshot(streamId: string, version: number, rules: number, state: unknown) {
    await this.#db.query(
      `INSERT INTO checkout_snapshot (stream_id, version, rules, state)
       VALUES ($1,$2,$3,$4)
       ON CONFLICT (stream_id, version, rules) DO NOTHING`,
      [streamId, version, rules, JSON.stringify(state)],
    );
  }

  /** Deletes what the current version does not use: the snapshots of another
   *  rules version, and all but the newest of each stream.
   *
   *  One single statement: in two —first the old ones, then those of another
   *  version— a prune interrupted halfway leaves a state nobody thought about.
   *  And it can be aggressive because a snapshot is a cache: the worst that
   *  happens is rebuilding from the stream. */
  async pruneSnapshots(rules: number) {
    const { rowCount } = await this.#db.query(
      `DELETE FROM checkout_snapshot s
        WHERE s.rules <> $1
           OR s.version < (SELECT max(version) FROM checkout_snapshot
                            WHERE stream_id = s.stream_id AND rules = $1)`,
      [rules],
    );
    return rowCount ?? 0;
  }

  async read(streamId: string, from = 0) {
    const { rows } = await this.#db.query(
      `SELECT version, type, data, at FROM checkout_event
        WHERE stream_id = $1 AND version > $2 ORDER BY version`,
      [streamId, from],
    );
    return rows.map((r: any) => ({
      version: Number(r.version),
      type: r.type as string,
      data: r.data as unknown,
      // when it HAPPENED. Rebuilding the view puts this one back, not the hour
      // of the rebuild.
      at: new Date(r.at).toISOString(),
    }));
  }

  /** The streams that exist, so they can be walked when rebuilding. */
  async streams() {
    const { rows } = await this.#db.query(
      `SELECT DISTINCT stream_id FROM checkout_event ORDER BY stream_id`,
    );
    return rows.map((r: any) => r.stream_id as string);
  }

  /** Records the event in the stream AND leaves it ready to publish, in ONE
   *  transaction. That is what makes there be no dual-write: the stream is the
   *  truth, the outbox is the delivery, and either both rows get in or neither
   *  does.
   *
   *  The generated outbox's `stage` takes this transaction, so the outbox row
   *  cannot commit without the event. */
  async append(streamId: string, expected: number, e: Envelope<unknown>) {
    const version = expected + 1;
    const c = await this.#db.connect();
    try {
      await c.query("BEGIN");
      await c.query(
        `INSERT INTO checkout_event (id, stream_id, version, type, data)
         VALUES ($1,$2,$3,$4,$5)`,
        [e.id, streamId, version, e.type, JSON.stringify(e.data)],
      );
      await this.#outbox.stage(e, c);
      await c.query("COMMIT");
    } catch (err: any) {
      await c.query("ROLLBACK").catch(() => {});
      // 23505: unique_violation. Somebody else wrote this version first, and
      // that is not a program error: it is the normal condition of two users on
      // the same aggregate.
      if (err?.code === "23505") throw new VersionConflict(streamId, expected);
      throw err;
    } finally {
      c.release();
    }
    return version;
  }
}

/** The domain's rules: how each event changes the state. It is the only thing
 *  the generator cannot know, and a declared event with no case does not
 *  compile. */
interface CheckoutState {
  state: "new" | "started" | "charged" | "compensated";
  cents: number;
  paymentId: string | null;
}

const checkoutRules: CheckoutRules<CheckoutState> = {
  initial: () => ({ state: "new", cents: 0, paymentId: null }),
  applyCheckoutStartedV1: (s, e) => ({ ...s, state: "started", cents: e.amount.amount }),
  applyCheckoutChargedV1: (s, e) => ({ ...s, state: "charged", paymentId: e.paymentId }),
  applyCheckoutCompensatedV1: (s) => ({ ...s, state: "compensated" }),
};

/** The projection. Each `apply*` saves the position in the SAME transaction as
 *  its effect: in two, a cut between them leaves the view ahead of or behind
 *  what it claims to have applied, and neither raises an error. */
class Conversion implements ConversionProjection, Checkpoint, Shadow {
  #db: pg.Pool;
  /** Which table it writes to. The shadow is ANOTHER instance, not a mode: a
   *  mode stays switched on and the next live projection writes into the shadow
   *  with nothing saying so. */
  #table: string;
  #view: string;
  constructor(db: pg.Pool, shadow = false) {
    this.#db = db;
    this.#table = shadow ? "view_conversion_shadow" : "view_conversion";
    this.#view = shadow ? "conversion_shadow" : "conversion";
  }

  /** Leaves the shadow empty, with its position at zero. */
  async prepare() {
    const c = await this.#db.connect();
    try {
      await c.query("BEGIN");
      await c.query(`DELETE FROM ${this.#table}`);
      await c.query(`DELETE FROM view_conversion_checkpoint WHERE view_name = $1`, [this.#view]);
      await c.query("COMMIT");
    } catch (err) {
      await c.query("ROLLBACK").catch(() => {});
      throw err;
    } finally {
      c.release();
    }
  }

  /** Swaps the shadow for the live one, and its position with it, in ONE
   *  transaction.
   *
   *  The swap is two RENAMEs and the handover of the position. Postgres allows
   *  transactional DDL, so whoever reads waits a few milliseconds instead of
   *  seeing a half-built view. In two transactions, a cut between them leaves
   *  the new table with the old one's position: it would skip events or
   *  reprocess them, and nothing would say so. */
  async swap() {
    const c = await this.#db.connect();
    try {
      await c.query("BEGIN");
      await c.query("ALTER TABLE view_conversion RENAME TO view_conversion_tmp");
      await c.query("ALTER TABLE view_conversion_shadow RENAME TO view_conversion");
      await c.query("ALTER TABLE view_conversion_tmp RENAME TO view_conversion_shadow");
      await c.query("DELETE FROM view_conversion_checkpoint WHERE view_name = 'conversion'");
      await c.query(
        `UPDATE view_conversion_checkpoint SET view_name = 'conversion'
          WHERE view_name = 'conversion_shadow'`,
      );
      await c.query("COMMIT");
    } catch (err) {
      await c.query("ROLLBACK").catch(() => {});
      throw err;
    } finally {
      c.release();
    }
  }

  async read(view: string, streamId: string) {
    const { rows } = await this.#db.query(
      `SELECT position FROM view_conversion_checkpoint
        WHERE view_name = $1 AND stream_id = $2`,
      [view, streamId],
    );
    return rows[0] ? Number(rows[0].position) : 0;
  }

  /** The view's effect and its position, in the SAME transaction. In two, a cut
   *  between them leaves the view ahead of or behind what it claims to have
   *  applied, and neither of those raises an error. */
  async #inOne(streamId: string, position: number, sql: string, args: unknown[]) {
    const c = await this.#db.connect();
    try {
      await c.query("BEGIN");
      await c.query(sql, args);
      await c.query(
        `INSERT INTO view_conversion_checkpoint (view_name, stream_id, position)
         VALUES ('${this.#view}', $1, $2)
         ON CONFLICT (view_name, stream_id)
         DO UPDATE SET position = GREATEST(view_conversion_checkpoint.position, $2)`,
        [streamId, position],
      );
      await c.query("COMMIT");
    } catch (err) {
      await c.query("ROLLBACK").catch(() => {});
      throw err;
    } finally {
      c.release();
    }
  }

  async applyCheckoutStartedV1(e: Envelope<any>, position: number) {
    // A demo switch: it stretches the rebuild so the window can be MEASURED.
    // Without it the rebuild finishes in milliseconds and "nobody saw anything"
    // cannot be told apart from "nobody looked".
    const slow = Number(process.env.AXON_DEMO_REBUILD_SLOW_MS ?? 0);
    if (slow > 0 && e.source === "rebuild") {
      await new Promise((r) => setTimeout(r, slow));
    }
    await this.#inOne(
      e.data.streamId,
      position,
      `INSERT INTO ${this.#table} (stream_id, state, cents, event_at)
       VALUES ($1,'started',$2,$3)
       ON CONFLICT (stream_id) DO UPDATE SET state = 'started', cents = $2, event_at = $3`,
      [e.data.streamId, e.data.amount.amount, e.time],
    );
  }

  async applyCheckoutChargedV1(e: Envelope<any>, position: number) {
    await this.#inOne(
      e.data.streamId,
      position,
      `UPDATE ${this.#table} SET state = 'charged', payment_id = $2, event_at = $3
        WHERE stream_id = $1`,
      [e.data.streamId, e.data.paymentId, e.time],
    );
  }

  async applyCheckoutCompensatedV1(e: Envelope<any>, position: number) {
    await this.#inOne(
      e.data.streamId,
      position,
      `UPDATE ${this.#table} SET state = 'compensated', reason = $2, event_at = $3
        WHERE stream_id = $1`,
      [e.data.streamId, e.data.reason, e.time],
    );
  }
}

/** Each step's inputs: the only thing the generator cannot know. The
 *  coordinator knows the order; it does not know the contents.
 *
 *  Everything comes from the envelope and from `prior`, never from a variable of
 *  this process: the sweep runs these same actions over a saga that started in
 *  ANOTHER process, and there a closure does not exist. */
function actions(clients: Clients): CheckoutActions {
  const input = (e: Envelope<unknown>) => e.data as CheckoutIn;
  return {
    async step1CapturePayment(e) {
      const { orderId, amount } = input(e);
      return clients.paymentsCapturePayment({ orderId, amount }, e);
    },
    async undo1RefundPayment(e, prior) {
      // with no charge there is nothing to undo, and that is not an error: the
      // coordinator also compensates the step that was left in doubt
      if (!prior.step1) return;
      await clients.paymentsRefundPayment({ paymentId: prior.step1.paymentId }, e);
    },
    async step2PayoutMerchant(e, prior) {
      if (!prior.step1) throw new Error("there is no charge to pay out");
      return clients.paymentsPayoutMerchant(
        { paymentId: prior.step1.paymentId, amount: input(e).amount },
        e,
      );
    },
  };
}

class Checkout extends CheckoutService {
  #journal: SagaJournal;
  #actions: CheckoutActions;
  #stream: Stream;
  #view: Conversion;
  #shadow: Conversion;
  constructor(b: any, o: Outbox<pg.PoolClient>, db: pg.Pool) {
    super(b, o);
    this.#journal = new Journal(db);
    this.#stream = new Stream(db, o);
    this.#view = new Conversion(db);
    this.#shadow = new Conversion(db, true);
    this.#actions = actions(new Clients(transport()));
  }

  get stream() {
    return this.#stream;
  }
  get view() {
    return this.#view;
  }
  get shadow() {
    return this.#shadow;
  }

  /** One event into the stream, and from there into the view.
   *
   *  The expected version comes from READING the stream, not from a counter in
   *  memory: with two instances, a local counter drifts and the UNIQUE is the
   *  only thing that says so. */
  async #record<T>(streamId: string, type: string, data: T, cause: Envelope<unknown>) {
    // `checkoutLoad` reads the last valid snapshot and only the rest of the
    // stream from there. With no snapshots it would read the whole stream, which
    // is the same thing until a stream has a hundred thousand events.
    const { version } = await checkoutLoad(checkoutRules, this.#stream, streamId);
    // The envelope is built BEFORE writing it. Nobody publishes here: the append
    // leaves the row in the outbox in the same transaction, and the relay
    // publishes from there. A `publish` on this line would be the dual-write all
    // of this avoids.
    const e = newEnvelope(type, "checkout", data, cause);
    const next = await this.#stream.append(streamId, version, e);
    // The snapshot is taken AFTER the append and from a freshly rebuilt state:
    // snapshotting what was believed to be the state before writing would save a
    // snapshot of something that did not end up in the stream.
    const { state } = await checkoutLoad(checkoutRules, this.#stream, streamId);
    await checkoutSnapshot(this.#stream, streamId, next, state);
    // The projection is applied right here. In a bigger system a separate
    // consumer would do it, and the checkpoint is exactly what makes it possible
    // to split them without reprocessing everything.
    await conversionApply(this.#view, e, next);
    return e;
  }

  get journal() {
    return this.#journal;
  }
  get steps() {
    return this.#actions;
  }

  async checkout(input: CheckoutIn, e: Envelope<unknown>): Promise<CheckoutOut> {
    // the saga's id is the stream's: the journal, the aggregate and the trace
    // talk about the same fact, and `axon trace` crosses them without guessing
    const stream = e.correlationId;
    await this.#record(stream, "checkout.started@v1",
      { streamId: stream, orderId: input.orderId, amount: input.amount }, e);
    // The generated coordinator throws SagaStuck: here it becomes the code the
    // manifest declares, so the caller reads `saga_stuck` and not a stringified
    // exception. It is the same 500 —it IS ours— but now it has a name.
    let r;
    try {
      r = await runCheckout(stream, this.#actions, this.#journal, e);
    } catch (err) {
      if (err instanceof SagaStuck) fail("checkout", "saga_stuck", String(err));
      throw err;
    }
    if (r.status === "completed") {
      const outputs = (await this.#journal.read(stream))?.outputs ?? {};
      const step1 = outputs[1] as { paymentId: string } | undefined;
      await this.#record(stream, "checkout.charged@v1",
        { streamId: stream, paymentId: step1?.paymentId ?? stream }, e);
    } else {
      await this.#record(stream, "checkout.compensated@v1",
        { streamId: stream, reason: String(r.error ?? "no reason") }, e);
    }
    return { state: r.status };
  }
}

if (process.env.NODE_TEST_CONTEXT === undefined) await main();

async function main() {
  startTelemetry();
  const db = await waitForDb();
  const b = bus(await connectBroker());
  const svc = new Checkout(b, outbox(), db);

  // The relay: the only thing that publishes. Without it, the events stay
  // recorded in the stream and in the outbox, and nobody receives them.
  relay(db, b);

  // Inside the process AND over the route the scheduler `axon infra` deploys
  // hits: a service scaled to zero sweeps nothing on its own.
  startSweepCheckout(svc.steps, svc.journal, (r) => {
    if (r.claimed) console.log(`[checkout] sweep ${JSON.stringify(r)}`);
    if (r.stuck) console.error(`[checkout] ${r.stuck} STUCK sagas`);
  });

  serve(
    Number(process.env.PORT ?? 8080),
    {
      // Discovery: the service publishes its own manifest at the path the
      // generated contract names. `axon discover <url>` merges that with what is
      // on disk, so a registry can be built from what is RUNNING and not from what
      // somebody remembered to commit.
      "GET /.well-known/axon.json": async () => manifest,
      "POST /v1/checkouts": (body, e) => svc.checkout(body, e),
      [sweepRouteCheckout]: () => sweepCheckout(svc.steps, svc.journal),
      // the route the cron `axon infra` deploys hits
      [pruneRouteCheckout]: async () => ({ deleted: await pruneCheckout(svc.stream) }),
      // Rebuilding carries no cron: it is not periodic, it is an operation
      // somebody decides on.
      [rebuildRouteConversion]: async () => ({
        applied: await rebuildConversion(svc.shadow, svc.stream),
      }),
    },
    httpRoutes,
    // the declared failures, projected as problem+json
    problem,
  );
}
